#ifndef TOOB_BOOT_CLOUD_CMD_H
#define TOOB_BOOT_CLOUD_CMD_H

#include "boot_hal.h"
#include "boot_types.h"
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Enum of all possible Cloud Commands.
 * Maps directly to the toob_cloud_cmd.cddl definition.
 */
typedef enum {
  TOOB_CMD_NOP = 0x00,          /* Heartbeat / Connectivity Test */
  TOOB_CMD_FORCE_UPDATE = 0x01, /* Erzwinge OTA beim nächsten Boot */
  TOOB_CMD_KILLSWITCH = 0x02,   /* Gerät sperren (Soft Lock) */
  TOOB_CMD_UNLOCK = 0x03,       /* Soft Lock aufheben */
  TOOB_CMD_ROTATE_KEY = 0x04,   /* Cloud-Key rotieren (eFuse!) */
  TOOB_CMD_WIPE = 0x05,         /* Factory Reset */
  TOOB_CMD_REVOKE = 0x06,       /* Hard Lock: DSLC → 0xFF (permanent!) */
} toob_cloud_cmd_t;

/**
 * @brief Structure representing the decoded Cloud Command Envelope.
 * Populated by boot_cloud_cmd_decode() generated by zcbor.
 */
typedef struct {
  uint8_t device_id[32];
  uint8_t command;
  uint32_t counter_min;
  uint32_t issued_at;
  uint8_t *params; /* Optional, dynamically pointing into payload */
  size_t params_len;
  uint8_t signature_ed25519[64];
} toob_cloud_cmd_envelope_t;

/**
 * @brief Key Delegation Manifest (KDM) for Cloud-Key Rotation.
 * Must be signed by the eFuse Root Key (Slot 0).
 */
typedef struct __attribute__((packed, aligned(8))) {
  uint32_t sequence_number;      /* TMR-protected sequence for anti-replay */
  uint8_t new_cloud_pubkey[32];  /* The new Ed25519 public key */
  uint8_t signature_ed25519[64]; /* Signature over [sequence_number | pubkey] by
                                    Root Key */
  uint8_t _padding[28]; /* Pad to 128 bytes for Flash Sector alignment */
} toob_kdm_t;

/* Mathematischer Beweis der KDM Flash-Alignment-Sicherheit */
_Static_assert(sizeof(toob_kdm_t) == 128,
               "KDM must be exactly 128 bytes for Flash Write Alignment");
_Static_assert(offsetof(toob_kdm_t, signature_ed25519) == 36,
               "KDM signed-data layout changed — update signing tool!");

/**
 * @brief Evaluates a Cloud Command Envelope directly from the Flash slot.
 *
 * TOCTOU-Safe: Reads the envelope entirely into the crypto_arena before
 * parsing.
 *
 * @param platform      Hardware platform pointer.
 * @param crypto_arena  Pointer to the secure SRAM block for zero-allocation
 * parsing.
 * @param out_cmd       Populated with the evaluated command intent (if BOOT_OK
 * is returned).
 * @return BOOT_OK on valid command, BOOT_ERR_VERIFY or others on failure.
 */
boot_status_t boot_cloud_cmd_evaluate_flash(const boot_platform_t *platform,
                                            uint8_t *crypto_arena,
                                            toob_cloud_cmd_t *out_cmd);

/**
 * @brief Evaluates a Cloud Command Envelope residing in a memory buffer.
 *
 * Used for UART 2FA Recovery (Unlock payload evaluation).
 *
 * @param platform      Hardware platform pointer.
 * @param envelope_buf  Pointer to the CBOR payload in RAM.
 * @param envelope_len  Length of the payload.
 * @param crypto_arena  Pointer to the secure SRAM block for zero-allocation
 * parsing.
 * @param out_cmd       Populated with the evaluated command intent.
 * @return BOOT_OK on valid command, BOOT_ERR_VERIFY or others on failure.
 */
boot_status_t boot_cloud_cmd_evaluate_buffer(const boot_platform_t *platform,
                                             const uint8_t *envelope_buf,
                                             size_t envelope_len,
                                             uint8_t *crypto_arena,
                                             toob_cloud_cmd_t *out_cmd);

#ifdef __cplusplus
}
#endif

#endif /* TOOB_BOOT_CLOUD_CMD_H */
