// Package lockfile manages the toob.lock file for reproducible builds.
//
// Format (TOML):
//
//	[registry]
//	commit = "a1b2c3d"
//
//	[chips.esp32c6]
//	version = "1.0.0"
//	arch = "riscv32"
//	vendor = "esp"
//	spawned = false
package lockfile

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

// ChipEntry holds the state of a single installed chip.
type ChipEntry struct {
	Version string `toml:"version"`
	Arch    string `toml:"arch"`
	Vendor  string `toml:"vendor"`
	Spawned bool   `toml:"spawned"`
}

// Lockfile is the in-memory representation of toob.lock.
type Lockfile struct {
	Registry struct {
		Version string `toml:"version"`
		Commit  string `toml:"commit"`
	} `toml:"registry"`
	Chips map[string]ChipEntry `toml:"chips"`
}

// Load parses an existing toob.lock. Returns an empty Lockfile if not found.
func Load(path string) (*Lockfile, error) {
	lf := &Lockfile{Chips: make(map[string]ChipEntry)}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return lf, nil
	}
	if _, err := toml.DecodeFile(path, lf); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", path, err)
	}
	if lf.Chips == nil {
		lf.Chips = make(map[string]ChipEntry)
	}
	return lf, nil
}

// Save writes the lockfile as TOML using a hand-rolled serializer to avoid
// pulling in a TOML encoder dependency.
func (lf *Lockfile) Save(path string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by toob CLI. Do not edit manually.\n\n")
	b.WriteString("[registry]\n")
	if lf.Registry.Version != "" {
		b.WriteString(fmt.Sprintf("version = %q\n", lf.Registry.Version))
	}
	b.WriteString(fmt.Sprintf("commit = %q\n\n", lf.Registry.Commit))

	names := make([]string, 0, len(lf.Chips))
	for n := range lf.Chips {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		e := lf.Chips[name]
		b.WriteString(fmt.Sprintf("[chips.%s]\n", name))
		b.WriteString(fmt.Sprintf("version = %q\n", e.Version))
		b.WriteString(fmt.Sprintf("arch = %q\n", e.Arch))
		b.WriteString(fmt.Sprintf("vendor = %q\n", e.Vendor))
		if e.Spawned {
			b.WriteString("spawned = true\n")
		} else {
			b.WriteString("spawned = false\n")
		}
		b.WriteString("\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// HasChip checks if a chip is installed.
func (lf *Lockfile) HasChip(name string) bool {
	_, ok := lf.Chips[name]
	return ok
}

// GetChip returns a chip entry or nil.
func (lf *Lockfile) GetChip(name string) *ChipEntry {
	e, ok := lf.Chips[name]
	if !ok {
		return nil
	}
	return &e
}

// IsArchShared returns true if any chip other than exclude uses the given arch.
func (lf *Lockfile) IsArchShared(arch, exclude string) bool {
	for name, e := range lf.Chips {
		if name != exclude && e.Arch == arch {
			return true
		}
	}
	return false
}

// IsVendorShared returns true if any chip other than exclude uses the given vendor.
func (lf *Lockfile) IsVendorShared(vendor, exclude string) bool {
	for name, e := range lf.Chips {
		if name != exclude && e.Vendor == vendor {
			return true
		}
	}
	return false
}
