[device]
vendor = "espressif"
chip = "esp32c6"

[partitions]
# Budgets in Bytes
stage0_size = 32768        # 32 KB
stage1_size = 65536        # 64 KB (Accepted 55KB footprint)
app_size = 393216          # 384 KB
recovery_size = 131072     # 128 KB
netcore_size = 65536       # 64 KB
enable_deltas = true       # Force Scratch Slot Generation
