package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/toob-boot/toob/internal/ui"
)

type MapEntry struct {
	Name string
	Addr uint32
	Size uint32
	Type string
}

func GenerateHeadersAndScripts(dt *DeviceToml, hj *HardwareJson, alloc *Allocator, outDir string,
	s0Addr, s0Budget, s1aAddr, s1bAddr, s1Budget, appAddr, stagingAddr, appBudget,
	recAddr, recBudget, netAddr, netBudget, scratchAddr, scratchSize, walAddr, walSize uint32,
	walAddrs []uint32, walSizes []uint32, kdmAddr, kdmBudget, cloudCmdAddr, cloudCmdBudget, mailboxAddr, mailboxBudget, forensicAddr, forensicBudget uint32) error {

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	flashSize := hj.Flash.Size
	maxSectorSize := alloc.maxSectorSize

	// Generate generated_boot_config.h
	headerPath := filepath.Join(outDir, "generated_boot_config.h")
	var b strings.Builder

	b.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	b.WriteString("#ifndef GENERATED_BOOT_CONFIG_H\n")
	b.WriteString("#define GENERATED_BOOT_CONFIG_H\n\n")
	b.WriteString("#include <stdint.h>\n\n")

	b.WriteString("/* ========================================================================\n")
	b.WriteString(" * PARTITION MAP (Auto-Generated by Manifest Compiler)\n")
	b.WriteString(" * ========================================================================\n")

	entries := []MapEntry{
		{"Stage 0", s0Addr, s0Budget, "BOOT"},
		{"Stage 1 Bank A", s1aAddr, s1Budget, "BOOT"},
		{"Stage 1 Bank B", s1bAddr, s1Budget, "BOOT"},
		{"App Slot", appAddr, appBudget, "APP"},
		{"Staging Slot", stagingAddr, appBudget, "APP"},
		{"Scratch / Delta Safe", scratchAddr, scratchSize, "SYSTEM"},
		{fmt.Sprintf("WAL Journal (%d sec)", dt.Partitions.WalSectors), walAddr, walSize, "SYSTEM"},
		{"KDM Quorum", kdmAddr, kdmBudget, "SYSTEM"},
		{"Cloud Command", cloudCmdAddr, cloudCmdBudget, "SYSTEM"},
		{"Mailbox", mailboxAddr, mailboxBudget, "SYSTEM"},
		{"Forensic Slot", forensicAddr, forensicBudget, "SYSTEM"},
	}
	if recBudget > 0 {
		entries = append(entries, MapEntry{"Recovery OS", recAddr, recBudget, "SYSTEM"})
	}
	if netBudget > 0 {
		entries = append(entries, MapEntry{"NetCore Slot", netAddr, netBudget, "APP"})
	}
	for _, r := range hj.Flash.Regions {
		if r.Type == "reserved" {
			name := r.Name
			if name == "" {
				name = "Hardware Reserved"
			}
			entries = append(entries, MapEntry{name, r.Base, r.Size, "RSVD"})
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Addr < entries[j].Addr
	})

	stats := map[string]uint32{"BOOT": 0, "SYSTEM": 0, "APP": 0, "RSVD": 0}
	for _, e := range entries {
		endAddr := e.Addr + e.Size
		stats[e.Type] += e.Size
		b.WriteString(fmt.Sprintf(" *   ├──────────────────────────────────────────────────┤ 0x%08X - 0x%08X\n", e.Addr, endAddr))
		b.WriteString(fmt.Sprintf(" *   │  [%-6s] %s (%d KB)\n", e.Type, e.Name, e.Size/1024))
	}

	b.WriteString(" *   └──────────────────────────────────────────────────┘ \n *\n")

	freeSpace := flashSize - alloc.CurrentOffset()
	b.WriteString(" * STORAGE SUMMARY:\n")
	b.WriteString(fmt.Sprintf(" *   Physical Flash Size:   %8d KB\n", flashSize/1024))
	b.WriteString(fmt.Sprintf(" *   Hardware Reserved:     %8d KB\n", stats["RSVD"]/1024))
	b.WriteString(fmt.Sprintf(" *   Bootloader Core:       %8d KB\n", stats["BOOT"]/1024))
	b.WriteString(fmt.Sprintf(" *   System & Scratch:      %8d KB\n", stats["SYSTEM"]/1024))
	b.WriteString(fmt.Sprintf(" *   Usable App Space:      %8d KB\n", stats["APP"]/1024))
	b.WriteString(fmt.Sprintf(" *   Unallocated / Free:    %8d KB\n", freeSpace/1024))
	b.WriteString(" * ======================================================================== */\n\n")

	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_WRITE_ALIGNMENT  %dU\n", hj.Flash.WriteAlignment))

	flashBase := hj.Flash.BaseAddr
	if flashBase == "" {
		flashBase = "0x00000000"
	}
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_BASE_ADDR        %sU\n\n", flashBase))

	stagingSlotID := dt.Partitions.StagingSlotID
	if stagingSlotID == 0 {
		stagingSlotID = 2
	}
	b.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_ID        %dU\n\n", stagingSlotID))

	walSectors := dt.Partitions.WalSectors
	if walSectors == 0 {
		walSectors = 4
	}
	b.WriteString(fmt.Sprintf("#define TOOB_WAL_SECTORS            %dU\n\n", walSectors))

	b.WriteString("#define TOOB_WAL_SECTOR_ADDRS { \\\n")
	for i, a := range walAddrs {
		comma := ","
		if i == len(walAddrs)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    0x%08XU%s \\\n", a, comma))
	}
	b.WriteString("}\n")

	b.WriteString("#define TOOB_WAL_SECTOR_SIZES { \\\n")
	for i, s := range walSizes {
		comma := ","
		if i == len(walSizes)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    %dU%s \\\n", s, comma))
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("#define BOOT_CRYPTO_ARENA_SIZE      %dU\n\n", hj.CryptoCapabilities.ArenaSize))

	wdtTimeout := dt.BootConfig.WdtTimeoutMs
	if wdtTimeout == 0 {
		wdtTimeout = 4100
	}
	b.WriteString(fmt.Sprintf("#define BOOT_WDT_TIMEOUT_MS         %dU\n\n", wdtTimeout))

	xipBase := hj.Flash.XipBase
	if xipBase == "" {
		xipBase = "0x0"
	}
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_XIP_BASE         %sU\n\n", xipBase))
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_TOTAL_SIZE       0x%08XU\n", flashSize))

	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_MAX_SECTOR_SIZE  %dU\n", maxSectorSize))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_MAX_RETRIES     %dU\n", dt.BootConfig.MaxRetries))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_MAX_RECOVERY_RETRIES %dU\n", dt.BootConfig.MaxRecoveryRetries))

	edgeMode := "0"
	if dt.BootConfig.EdgeUnattendedMode {
		edgeMode = "1"
	}
	fmt.Fprintf(&b, "#define BOOT_CONFIG_EDGE_UNATTENDED_MODE %s\n", edgeMode)
	fmt.Fprintf(&b, "#define BOOT_CONFIG_BACKOFF_BASE_S  %dU\n", dt.BootConfig.BackoffBaseS)
	b.WriteString(fmt.Sprintf("#define BOOT_STAGE1_SVN             %dU\n", dt.BootConfig.Stage1Svn))

	if dt.BootConfig.TransportProvider != "" {
		b.WriteString(fmt.Sprintf("#define TOOB_TRANSPORT_PROVIDER     TOOB_TRANSPORT_%s\n", strings.ToUpper(dt.BootConfig.TransportProvider)))
	}

	// P7d: Crypto-Backend Compile-Time Gating
	pqcEnabled := "0"
	if dt.Crypto.Pqc != "" {
		pqcEnabled = "1"
	}
	b.WriteString(fmt.Sprintf("#define TOOB_PQC_ENABLED            %s\n", pqcEnabled))
	if dt.Crypto.Backend != "" {
		b.WriteString(fmt.Sprintf("#define TOOB_CRYPTO_BACKEND         \"%s\"\n", dt.Crypto.Backend))
	}
	b.WriteString("\n")

	// Write fields that dynamic drivers use from Toml/Json
	if len(hj.Registers) > 0 {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * HARDWARE REGISTERS (Dynamic from hardware.json)\n")
		b.WriteString(" * ======================================================================== */\n")
		var regKeys []string
		for k := range hj.Registers {
			regKeys = append(regKeys, k)
		}
		sort.Strings(regKeys)
		for _, k := range regKeys {
			macroName := "CHIP_REG_" + strings.ToUpper(k)
			v := hj.Registers[k]
			switch val := v.(type) {
			case string:
				b.WriteString(fmt.Sprintf("#define %-30s %sU\n", macroName, val))
			case float64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			}
		}
		b.WriteString("\n")
	}

	if len(hj.Constants) > 0 {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * CHIP CONSTANTS (Dynamic from hardware.json)\n")
		b.WriteString(" * ======================================================================== */\n")
		var constKeys []string
		for k := range hj.Constants {
			constKeys = append(constKeys, k)
		}
		sort.Strings(constKeys)
		for _, k := range constKeys {
			macroName := "CHIP_" + strings.ToUpper(k)
			v := hj.Constants[k]
			switch val := v.(type) {
			case string:
				b.WriteString(fmt.Sprintf("#define %-30s %sU\n", macroName, val))
			case float64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			}
		}
		b.WriteString("\n")
	}

	if dt.DriverConfig != nil {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * USER DRIVER CONFIGURATION (Dynamic from device.toml)\n")
		b.WriteString(" * ======================================================================== */\n")
		var drvKeys []string
		for k := range dt.DriverConfig {
			drvKeys = append(drvKeys, k)
		}
		sort.Strings(drvKeys)
		for _, k := range drvKeys {
			macroName := "TOOB_DRIVER_" + strings.ToUpper(k)
			v := dt.DriverConfig[k]
			switch val := v.(type) {
			case string:
				b.WriteString(fmt.Sprintf("#define %-30s %s\n", macroName, val))
			case int64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			case float64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			case bool:
				if val {
					b.WriteString(fmt.Sprintf("#define %-30s 1\n", macroName))
				} else {
					b.WriteString(fmt.Sprintf("#define %-30s 0\n", macroName))
				}
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("#include \"boot_layout.h\"\n")
	b.WriteString("#include \"boot_layout_assert.h\"\n\n")

	b.WriteString("#endif /* GENERATED_BOOT_CONFIG_H */\n")

	if err := writeFileIfChanged(headerPath, []byte(b.String())); err != nil {
		return err
	}

	// Generate boot_layout.h
	layoutPath := filepath.Join(outDir, "boot_layout.h")
	var lob strings.Builder
	lob.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER — DO NOT EDIT */\n")
	lob.WriteString("#ifndef BOOT_LAYOUT_H\n")
	lob.WriteString("#define BOOT_LAYOUT_H\n\n")

	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE0_ABS_ADDR         0x%08XU\n", s0Addr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE0_SIZE             0x%08XU\n", s0Budget))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1A_ABS_ADDR        0x%08XU\n", s1aAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1A_SIZE            0x%08XU\n", s1Budget))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1B_ABS_ADDR        0x%08XU\n", s1bAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1B_SIZE            0x%08XU\n\n", s1Budget))

	lob.WriteString(fmt.Sprintf("#define CHIP_APP_SLOT_ABS_ADDR       0x%08XU\n", appAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_APP_SLOT_SIZE           0x%08XU\n", appBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_ABS_ADDR   0x%08XU\n", stagingAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_SIZE       0x%08XU\n\n", appBudget))

	lob.WriteString(fmt.Sprintf("#define CHIP_SCRATCH_SLOT_ABS_ADDR   0x%08XU\n", scratchAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_SCRATCH_SLOT_SIZE       0x%08XU\n\n", scratchSize))

	lob.WriteString(fmt.Sprintf("#define CHIP_WAL_ABS_ADDR            0x%08XU\n", walAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_WAL_SIZE                0x%08XU\n\n", walSize))

	for i, a := range walAddrs {
		lob.WriteString(fmt.Sprintf("#define CHIP_WAL_SECTOR_%d_ADDR       0x%08XU\n", i, a))
		lob.WriteString(fmt.Sprintf("#define CHIP_WAL_SECTOR_%d_SIZE       0x%08XU\n", i, walSizes[i]))
	}
	lob.WriteString("\n")

	lob.WriteString(fmt.Sprintf("#define CHIP_RECOVERY_OS_ABS_ADDR    0x%08XU\n", recAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_RECOVERY_OS_SIZE        0x%08XU\n", recBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_NETCORE_SLOT_ABS_ADDR   0x%08XU\n", netAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_NETCORE_SLOT_SIZE       0x%08XU\n\n", netBudget))

	lob.WriteString(fmt.Sprintf("#define CHIP_KDM_QUORUM_ABS_ADDR     0x%08XU\n", kdmAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_KDM_QUORUM_SIZE         0x%08XU\n", kdmBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_CLOUD_CMD_SLOT_ABS_ADDR 0x%08XU\n", cloudCmdAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_CLOUD_CMD_SLOT_SIZE     0x%08XU\n\n", cloudCmdBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_MAILBOX_ABS_ADDR        0x%08XU\n", mailboxAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_MAILBOX_SLOT_SIZE       0x%08XU\n", mailboxBudget/2))
	lob.WriteString(fmt.Sprintf("#define CHIP_MAILBOX_SIZE            0x%08XU\n\n", mailboxBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_FORENSIC_SLOT_ABS_ADDR  0x%08XU\n", forensicAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_FORENSIC_SLOT_SIZE      0x%08XU\n\n", forensicBudget))



	lob.WriteString("#endif /* BOOT_LAYOUT_H */\n")

	if err := writeFileIfChanged(layoutPath, []byte(lob.String())); err != nil {
		return err
	}

	// Generate boot_layout_assert.h
	assertPath := filepath.Join(outDir, "boot_layout_assert.h")
	var aob strings.Builder
	aob.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER — DO NOT EDIT */\n")
	aob.WriteString("#ifndef BOOT_LAYOUT_ASSERT_H\n")
	aob.WriteString("#define BOOT_LAYOUT_ASSERT_H\n\n")
	aob.WriteString("#include \"boot_layout.h\"\n\n")

	aob.WriteString("/* Helper macro to assert two regions do not overlap (if size > 0) */\n")
	aob.WriteString("#define BOOT_CHECK_DISJOINT(a_base, a_size, b_base, b_size) \\\n")
	aob.WriteString("    ( ((a_size) == 0) || ((b_size) == 0) || \\\n")
	aob.WriteString("      ((a_base) + (a_size) <= (b_base)) || ((b_base) + (b_size) <= (a_base)) )\n\n")

	type RegMeta struct {
		Name string
		Base string
		Size string
	}
	regMetas := []RegMeta{
		{"Stage 0", "CHIP_STAGE0_ABS_ADDR", "CHIP_STAGE0_SIZE"},
		{"Stage 1 Bank A", "CHIP_STAGE1A_ABS_ADDR", "CHIP_STAGE1A_SIZE"},
		{"Stage 1 Bank B", "CHIP_STAGE1B_ABS_ADDR", "CHIP_STAGE1B_SIZE"},
		{"App Slot", "CHIP_APP_SLOT_ABS_ADDR", "CHIP_APP_SLOT_SIZE"},
		{"Staging Slot", "CHIP_STAGING_SLOT_ABS_ADDR", "CHIP_STAGING_SLOT_SIZE"},
		{"Scratch Slot", "CHIP_SCRATCH_SLOT_ABS_ADDR", "CHIP_SCRATCH_SLOT_SIZE"},
		{"WAL Journal", "CHIP_WAL_ABS_ADDR", "CHIP_WAL_SIZE"},
		{"Recovery OS", "CHIP_RECOVERY_OS_ABS_ADDR", "CHIP_RECOVERY_OS_SIZE"},
		{"NetCore Slot", "CHIP_NETCORE_SLOT_ABS_ADDR", "CHIP_NETCORE_SLOT_SIZE"},
		{"KDM Quorum", "CHIP_KDM_QUORUM_ABS_ADDR", "CHIP_KDM_QUORUM_SIZE"},
		{"Cloud Command", "CHIP_CLOUD_CMD_SLOT_ABS_ADDR", "CHIP_CLOUD_CMD_SLOT_SIZE"},
		{"Mailbox", "CHIP_MAILBOX_ABS_ADDR", "CHIP_MAILBOX_SIZE"},
		{"Forensic Slot", "CHIP_FORENSIC_SLOT_ABS_ADDR", "CHIP_FORENSIC_SLOT_SIZE"},
	}

	aob.WriteString("/* 1. Pairwise Disjointness (Overlap-Free) Assertions */\n")
	for i := 0; i < len(regMetas); i++ {
		for j := i + 1; j < len(regMetas); j++ {
			aob.WriteString(fmt.Sprintf("_Static_assert(BOOT_CHECK_DISJOINT(%s, %s, %s, %s),\n",
				regMetas[i].Base, regMetas[i].Size, regMetas[j].Base, regMetas[j].Size))
			aob.WriteString(fmt.Sprintf("               \"Layout Overlap: %s and %s overlap!\");\n",
				regMetas[i].Name, regMetas[j].Name))
		}
	}
	aob.WriteString("\n")

	aob.WriteString("/* 2. Sector Alignment Assertions (Base address must be a multiple of sector size) */\n")
	for _, r := range regMetas {
		aob.WriteString(fmt.Sprintf("_Static_assert(%s == 0 || (%s %% CHIP_FLASH_MAX_SECTOR_SIZE) == 0,\n", r.Size, r.Base))
		aob.WriteString(fmt.Sprintf("               \"Layout Alignment: %s is not aligned to CHIP_FLASH_MAX_SECTOR_SIZE!\");\n", r.Name))
	}
	aob.WriteString("\n")

	aob.WriteString("/* 3. Minimum Size Assertions */\n")
	aob.WriteString("_Static_assert(TOOB_WAL_SECTORS >= 4,\n")
	aob.WriteString("               \"WAL minimum size: TOOB_WAL_SECTORS must be >= 4!\");\n")
	for i := range walAddrs {
		aob.WriteString(fmt.Sprintf("_Static_assert(CHIP_WAL_SECTOR_%d_SIZE >= 128,\n", i))
		aob.WriteString(fmt.Sprintf("               \"WAL sector %d minimum size: must be >= 128 bytes (Header+Entry)!\");\n", i))
	}
	aob.WriteString("_Static_assert(CHIP_SCRATCH_SLOT_SIZE >= CHIP_FLASH_MAX_SECTOR_SIZE,\n")
	aob.WriteString("               \"Scratch Slot minimum size: must be >= CHIP_FLASH_MAX_SECTOR_SIZE!\");\n")
	aob.WriteString("_Static_assert(CHIP_KDM_QUORUM_SIZE >= 3 * CHIP_FLASH_MAX_SECTOR_SIZE,\n")
	aob.WriteString("               \"KDM Quorum minimum size: must be >= 3 sectors for Phase 4 quorum!\");\n\n")

	aob.WriteString("/* 4. Wrap-Around / Overflow Protection */\n")
	for _, r := range regMetas {
		aob.WriteString(fmt.Sprintf("_Static_assert(%s + %s >= %s,\n", r.Base, r.Size, r.Base))
		aob.WriteString(fmt.Sprintf("               \"Layout Overflow: %s address range wraps around!\");\n", r.Name))
	}
	aob.WriteString("\n")

	aob.WriteString("#endif /* BOOT_LAYOUT_ASSERT_H */\n")

	if err := writeFileIfChanged(assertPath, []byte(aob.String())); err != nil {
		return err
	}

	// Generate generated_memory.ld
	ldPath := filepath.Join(outDir, "generated_memory.ld")
	var ldb strings.Builder
	ldb.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	ldb.WriteString(fmt.Sprintf("__S0_BUDGET_START = 0x%08X;\n", s0Addr))
	ldb.WriteString(fmt.Sprintf("__S0_BUDGET_SIZE = 0x%08X;\n", s0Budget))
	ldb.WriteString(fmt.Sprintf("__S1A_BUDGET_START = 0x%08X;\n", s1aAddr))
	ldb.WriteString(fmt.Sprintf("__S1B_BUDGET_START = 0x%08X;\n", s1bAddr))
	ldb.WriteString(fmt.Sprintf("__S1_BUDGET_SIZE = 0x%08X;\n", s1Budget))
	ldb.WriteString(fmt.Sprintf("__APP_BUDGET_START = 0x%08X;\n", appAddr))
	ldb.WriteString(fmt.Sprintf("__APP_BUDGET_SIZE = 0x%08X;\n", appBudget))
	if err := writeFileIfChanged(ldPath, []byte(ldb.String())); err != nil {
		return err
	}

	// Generate stage0_layout.ld
	stage0LdPath := filepath.Join(outDir, "stage0_layout.ld")
	var s0ld strings.Builder
	s0ld.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	s0ld.WriteString("/* Valid Stage 0 Layout */\n")
	s0ld.WriteString("ENTRY(main)\n\n")
	s0ld.WriteString("INCLUDE generated_memory.ld\n\n")
	s0ld.WriteString("MEMORY {\n")
	s0ld.WriteString(fmt.Sprintf("    S0_RAM (rwx) : ORIGIN = %s, LENGTH = %s\n", hj.Memory.RamBase, hj.Memory.RamSize))
	s0ld.WriteString("    S0_ROM (rx)  : ORIGIN = __S0_BUDGET_START, LENGTH = __S0_BUDGET_SIZE\n")
	s0ld.WriteString("}\n\n")
	s0ld.WriteString("SECTIONS {\n")
	s0ld.WriteString("    .text : {\n")
	s0ld.WriteString("        KEEP(*(.text.main))\n")
	s0ld.WriteString("        *(.text .text.*)\n")
	s0ld.WriteString("    } > S0_ROM\n\n")
	s0ld.WriteString("    .rodata : {\n")
	s0ld.WriteString("        *(.rodata .rodata.*)\n")
	s0ld.WriteString("        *(.srodata .srodata.*)\n")
	s0ld.WriteString("    } > S0_ROM\n\n")
	s0ld.WriteString("    .data : {\n")
	s0ld.WriteString("        *(.data .data.*)\n")
	s0ld.WriteString("        *(.sdata .sdata.*)\n")
	s0ld.WriteString("    } > S0_RAM AT > S0_ROM\n\n")
	s0ld.WriteString("    .bss (NOLOAD) : {\n")
	s0ld.WriteString("        *(.bss .bss.*)\n")
	s0ld.WriteString("        *(.sbss .sbss.*)\n")
	s0ld.WriteString("        *(COMMON)\n")
	s0ld.WriteString("    } > S0_RAM\n\n")
	s0ld.WriteString("    .toob_mock_section : {\n")
	s0ld.WriteString("        KEEP(*(.toob_mock_section))\n")
	s0ld.WriteString("    } > S0_ROM\n")
	s0ld.WriteString("}\n")
	if err := writeFileIfChanged(stage0LdPath, []byte(s0ld.String())); err != nil {
		return err
	}

	return nil
}

func writeFileIfChanged(path string, data []byte) error {
	if old, err := os.ReadFile(path); err == nil && string(old) == string(data) {
		return nil
	}
	return os.WriteFile(path, data, 0o644)
}

func VerifyMacroUsage(headerPath, bootloaderDir, halChipDir string, extraDirs []string) error {
	ui.Step("Validating macro consumption in C code...")

	data, err := os.ReadFile(headerPath)
	if err != nil {
		return err
	}
	content := string(data)

	re := regexp.MustCompile(`#define\s+(CHIP_[A-Z0-9_]+|BOOT_[A-Z0-9_]+|TOOB_[A-Z0-9_]+)`)
	matches := re.FindAllStringSubmatch(content, -1)
	macros := make(map[string]bool)
	for _, m := range matches {
		if len(m) > 1 && m[1] != "GENERATED_BOOT_CONFIG_H" {
			macros[m[1]] = false // not used yet
		}
	}

	dirsToWalk := []string{bootloaderDir}
	if halChipDir != "" {
		dirsToWalk = append(dirsToWalk, halChipDir)
	}
	dirsToWalk = append(dirsToWalk, extraDirs...)

	var errAllFound = fmt.Errorf("all macros found")
	for _, dir := range dirsToWalk {
		walkErr := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return nil
			}
			if !d.IsDir() && (strings.HasSuffix(d.Name(), ".c") || strings.HasSuffix(d.Name(), ".h")) {
				b, err := os.ReadFile(path)
				if err == nil {
					text := string(b)
					allUsed := true
					for m, used := range macros {
						if !used {
							if strings.Contains(text, m) {
								macros[m] = true
							} else {
								allUsed = false
							}
						}
					}
					if allUsed {
						return errAllFound
					}
				}
			}
			return nil
		})
		if walkErr == errAllFound {
			break
		}
		if walkErr != nil {
			return walkErr
		}
	}

	var unreferenced []string
	for m, used := range macros {
		if !used {
			unreferenced = append(unreferenced, m)
		}
	}

	if len(unreferenced) > 0 {
		sort.Strings(unreferenced)
		var errb strings.Builder
		errb.WriteString("\n======================================================================\n")
		errb.WriteString("FATAL ERROR: MANIFEST COMPILER FAIL-FAST TRIGGERED!\n")
		errb.WriteString("The following macros were generated but NEVER referenced in the C code:\n")
		for _, m := range unreferenced {
			errb.WriteString(fmt.Sprintf("  - %s\n", m))
		}
		errb.WriteString("=\nThis indicates a severe architectural gap! Either:\n")
		errb.WriteString("  1. The C code is using a hardcoded fallback and ignoring the manifest.\n")
		errb.WriteString("  2. The manifest is generating dead code that should be pruned.\n")
		errb.WriteString("  3. You are developing/building locally and the registry sources in the cache (~/.toob/registry) are out of sync with your local registry. Ensure TOOB_REGISTRY_DIR points to your local registry directory!\n")
		errb.WriteString("Fix the C code to use these macros, or remove them from the generator.\n")
		errb.WriteString("======================================================================\n")
		return fmt.Errorf("%s", errb.String())
	}

	ui.Success("All generated macros are perfectly synchronized with the C code!")
	return nil
}
