package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type MapEntry struct {
	Name string
	Addr uint32
	Size uint32
	Type string
}

func GenerateHeadersAndScripts(dt *DeviceToml, hj *HardwareJson, alloc *Allocator, outDir string, 
	s0Addr, s0Budget, s1aAddr, s1bAddr, s1Budget, appAddr, stagingAddr, appBudget, 
	recAddr, recBudget, netAddr, netBudget, scratchAddr, scratchSize, walAddr, walSize uint32,
	walAddrs []uint32, walSizes []uint32) error {

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	flashSize := hj.Flash.Size
	maxSectorSize := alloc.maxSectorSize

	// Generate generated_boot_config.h
	headerPath := filepath.Join(outDir, "generated_boot_config.h")
	var b strings.Builder

	b.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	b.WriteString("#ifndef GENERATED_BOOT_CONFIG_H\n")
	b.WriteString("#define GENERATED_BOOT_CONFIG_H\n\n")
	b.WriteString("#include <stdint.h>\n\n")

	b.WriteString("/* ========================================================================\n")
	b.WriteString(" * PARTITION MAP (Auto-Generated by Manifest Compiler)\n")
	b.WriteString(" * ========================================================================\n")

	entries := []MapEntry{
		{"Stage 0", s0Addr, s0Budget, "BOOT"},
		{"Stage 1 Bank A", s1aAddr, s1Budget, "BOOT"},
		{"Stage 1 Bank B", s1bAddr, s1Budget, "BOOT"},
		{"App Slot", appAddr, appBudget, "APP"},
		{"Staging Slot", stagingAddr, appBudget, "APP"},
		{"Scratch / Delta Safe", scratchAddr, scratchSize, "SYSTEM"},
		{fmt.Sprintf("WAL Journal (%d sec)", dt.Partitions.WalSectors), walAddr, walSize, "SYSTEM"},
	}
	if recBudget > 0 {
		entries = append(entries, MapEntry{"Recovery OS", recAddr, recBudget, "SYSTEM"})
	}
	if netBudget > 0 {
		entries = append(entries, MapEntry{"NetCore Slot", netAddr, netBudget, "APP"})
	}
	for _, r := range hj.Flash.Regions {
		if r.Type == "reserved" {
			name := r.Name
			if name == "" {
				name = "Hardware Reserved"
			}
			entries = append(entries, MapEntry{name, r.Base, r.Size, "RSVD"})
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Addr < entries[j].Addr
	})

	stats := map[string]uint32{"BOOT": 0, "SYSTEM": 0, "APP": 0, "RSVD": 0}
	for _, e := range entries {
		endAddr := e.Addr + e.Size
		stats[e.Type] += e.Size
		b.WriteString(fmt.Sprintf(" *   ├──────────────────────────────────────────────────┤ 0x%08X - 0x%08X\n", e.Addr, endAddr))
		b.WriteString(fmt.Sprintf(" *   │  [%-6s] %s (%d KB)\n", e.Type, e.Name, e.Size/1024))
	}

	b.WriteString(" *   └──────────────────────────────────────────────────┘ \n *\n")

	freeSpace := flashSize - alloc.CurrentOffset()
	b.WriteString(" * STORAGE SUMMARY:\n")
	b.WriteString(fmt.Sprintf(" *   Physical Flash Size:   %8d KB\n", flashSize/1024))
	b.WriteString(fmt.Sprintf(" *   Hardware Reserved:     %8d KB\n", stats["RSVD"]/1024))
	b.WriteString(fmt.Sprintf(" *   Bootloader Core:       %8d KB\n", stats["BOOT"]/1024))
	b.WriteString(fmt.Sprintf(" *   System & Scratch:      %8d KB\n", stats["SYSTEM"]/1024))
	b.WriteString(fmt.Sprintf(" *   Usable App Space:      %8d KB\n", stats["APP"]/1024))
	b.WriteString(fmt.Sprintf(" *   Unallocated / Free:    %8d KB\n", freeSpace/1024))
	b.WriteString(" * ======================================================================== */\n\n")

	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_WRITE_ALIGNMENT  %dU\n", hj.Flash.WriteAlignment))
	
	flashBase := hj.Flash.BaseAddr
	if flashBase == "" {
		flashBase = "0x00000000"
	}
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_BASE_ADDR        %sU\n\n", flashBase))

	b.WriteString(fmt.Sprintf("#define CHIP_STAGE1A_ABS_ADDR       0x%08XU\n", s1aAddr))
	b.WriteString(fmt.Sprintf("#define CHIP_STAGE1A_SIZE           0x%08XU\n", s1Budget))
	b.WriteString(fmt.Sprintf("#define CHIP_STAGE1B_ABS_ADDR       0x%08XU\n", s1bAddr))
	b.WriteString(fmt.Sprintf("#define CHIP_STAGE1B_SIZE           0x%08XU\n\n", s1Budget))

	b.WriteString(fmt.Sprintf("#define CHIP_APP_SLOT_ABS_ADDR      0x%08XU\n", appAddr))
	b.WriteString(fmt.Sprintf("#define CHIP_APP_SLOT_SIZE          0x%08XU\n", appBudget))
	b.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_ABS_ADDR  0x%08XU\n", stagingAddr))
	b.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_SIZE      0x%08XU\n", appBudget))
	
	stagingSlotID := dt.Partitions.StagingSlotID
	if stagingSlotID == 0 {
		stagingSlotID = 2
	}
	b.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_ID        %dU\n\n", stagingSlotID))

	b.WriteString(fmt.Sprintf("#define CHIP_RECOVERY_OS_ABS_ADDR   0x%08XU\n", recAddr))
	b.WriteString(fmt.Sprintf("#define CHIP_RECOVERY_OS_SIZE       0x%08XU\n", recBudget))
	b.WriteString(fmt.Sprintf("#define CHIP_NETCORE_SLOT_ABS_ADDR  0x%08XU\n", netAddr))
	b.WriteString(fmt.Sprintf("#define CHIP_NETCORE_SLOT_SIZE      0x%08XU\n\n", netBudget))

	b.WriteString("/* CRITICAL: Must be >= CHIP_APP_SLOT_SIZE for boot_delta_apply output */\n")
	b.WriteString(fmt.Sprintf("#define CHIP_SCRATCH_SLOT_ABS_ADDR  0x%08XU\n\n", scratchAddr))

	walSectors := dt.Partitions.WalSectors
	if walSectors == 0 {
		walSectors = 4
	}
	b.WriteString(fmt.Sprintf("#define TOOB_WAL_SECTORS            %dU\n\n", walSectors))

	b.WriteString("#define TOOB_WAL_SECTOR_ADDRS { \\\n")
	for i, a := range walAddrs {
		comma := ","
		if i == len(walAddrs)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    0x%08XU%s \\\n", a, comma))
	}
	b.WriteString("}\n")

	b.WriteString("#define TOOB_WAL_SECTOR_SIZES { \\\n")
	for i, s := range walSizes {
		comma := ","
		if i == len(walSizes)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    %dU%s \\\n", s, comma))
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("#define BOOT_CRYPTO_ARENA_SIZE      %dU\n\n", hj.CryptoCapabilities.ArenaSize))
	
	wdtTimeout := dt.BootConfig.WdtTimeoutMs
	if wdtTimeout == 0 {
		wdtTimeout = 4100
	}
	b.WriteString(fmt.Sprintf("#define BOOT_WDT_TIMEOUT_MS         %dU\n\n", wdtTimeout))

	xipBase := hj.Flash.XipBase
	if xipBase == "" {
		xipBase = "0x0"
	}
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_XIP_BASE         %sU\n\n", xipBase))
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_TOTAL_SIZE       0x%08XU\n", flashSize))

	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_MAX_SECTOR_SIZE  %dU\n", maxSectorSize))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_MAX_RETRIES     %dU\n", dt.BootConfig.MaxRetries))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_MAX_RECOVERY_RETRIES %dU\n", dt.BootConfig.MaxRecoveryRetries))
	
	edgeMode := "0"
	if dt.BootConfig.EdgeUnattendedMode {
		edgeMode = "1"
	}
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_EDGE_UNATTENDED_MODE %s\n", edgeMode))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_BACKOFF_BASE_S  %dU\n\n", dt.BootConfig.BackoffBaseS))

	b.WriteString("#endif /* GENERATED_BOOT_CONFIG_H */\n")

	if err := os.WriteFile(headerPath, []byte(b.String()), 0o644); err != nil {
		return err
	}

	// Generate generated_memory.ld
	ldPath := filepath.Join(outDir, "generated_memory.ld")
	var ldb strings.Builder
	ldb.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	ldb.WriteString(fmt.Sprintf("__S0_BUDGET_START = 0x%08X;\n", s0Addr))
	ldb.WriteString(fmt.Sprintf("__S0_BUDGET_SIZE = 0x%08X;\n", s0Budget))
	ldb.WriteString(fmt.Sprintf("__S1A_BUDGET_START = 0x%08X;\n", s1aAddr))
	ldb.WriteString(fmt.Sprintf("__S1B_BUDGET_START = 0x%08X;\n", s1bAddr))
	ldb.WriteString(fmt.Sprintf("__S1_BUDGET_SIZE = 0x%08X;\n", s1Budget))
	ldb.WriteString(fmt.Sprintf("__APP_BUDGET_START = 0x%08X;\n", appAddr))
	ldb.WriteString(fmt.Sprintf("__APP_BUDGET_SIZE = 0x%08X;\n", appBudget))
	if err := os.WriteFile(ldPath, []byte(ldb.String()), 0o644); err != nil {
		return err
	}

	// Generate stage0_layout.ld
	stage0LdPath := filepath.Join(outDir, "stage0_layout.ld")
	var s0ld strings.Builder
	s0ld.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	s0ld.WriteString("/* Valid Stage 0 Layout */\n")
	s0ld.WriteString("ENTRY(main)\n\n")
	s0ld.WriteString("INCLUDE generated_memory.ld\n\n")
	s0ld.WriteString("MEMORY {\n")
	s0ld.WriteString(fmt.Sprintf("    S0_RAM (rwx) : ORIGIN = %s, LENGTH = %s\n", hj.Memory.RamBase, hj.Memory.RamSize))
	s0ld.WriteString("    S0_ROM (rx)  : ORIGIN = __S0_BUDGET_START, LENGTH = __S0_BUDGET_SIZE\n")
	s0ld.WriteString("}\n\n")
	s0ld.WriteString("SECTIONS {\n")
	s0ld.WriteString("    .text : {\n")
	s0ld.WriteString("        KEEP(*(.text.main))\n")
	s0ld.WriteString("        *(.text .text.*)\n")
	s0ld.WriteString("    } > S0_ROM\n\n")
	s0ld.WriteString("    .rodata : {\n")
	s0ld.WriteString("        *(.rodata .rodata.*)\n")
	s0ld.WriteString("        *(.srodata .srodata.*)\n")
	s0ld.WriteString("    } > S0_ROM\n\n")
	s0ld.WriteString("    .data : {\n")
	s0ld.WriteString("        *(.data .data.*)\n")
	s0ld.WriteString("        *(.sdata .sdata.*)\n")
	s0ld.WriteString("    } > S0_RAM AT > S0_ROM\n\n")
	s0ld.WriteString("    .bss (NOLOAD) : {\n")
	s0ld.WriteString("        *(.bss .bss.*)\n")
	s0ld.WriteString("        *(.sbss .sbss.*)\n")
	s0ld.WriteString("        *(COMMON)\n")
	s0ld.WriteString("    } > S0_RAM\n\n")
	s0ld.WriteString("    .toob_mock_section : {\n")
	s0ld.WriteString("        KEEP(*(.toob_mock_section))\n")
	s0ld.WriteString("    } > S0_ROM\n")
	s0ld.WriteString("}\n")
	if err := os.WriteFile(stage0LdPath, []byte(s0ld.String()), 0o644); err != nil {
		return err
	}

	return nil
}

func VerifyMacroUsage(headerPath, bootloaderDir string) error {
	fmt.Println("[Manifest Verifier] Validating macro consumption in C code...")

	data, err := os.ReadFile(headerPath)
	if err != nil {
		return err
	}
	content := string(data)

	re := regexp.MustCompile(`#define\s+(CHIP_[A-Z0-9_]+|BOOT_[A-Z0-9_]+|TOOB_[A-Z0-9_]+)`)
	matches := re.FindAllStringSubmatch(content, -1)
	macros := make(map[string]bool)
	for _, m := range matches {
		if len(m) > 1 && m[1] != "GENERATED_BOOT_CONFIG_H" {
			macros[m[1]] = false // not used yet
		}
	}

	commentRe := regexp.MustCompile(`(?s)/\*.*?\*/|//[^\n]*\n`)

	err = filepath.WalkDir(bootloaderDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if !d.IsDir() && (strings.HasSuffix(d.Name(), ".c") || strings.HasSuffix(d.Name(), ".h")) {
			b, err := os.ReadFile(path)
			if err == nil {
				text := string(b)
				// Strip comments before checking for macro presence to avoid "comment bypass"
				cleanText := commentRe.ReplaceAllString(text, "")
				for m, used := range macros {
					if !used && strings.Contains(cleanText, m) {
						macros[m] = true
					}
				}
			}
		}
		return nil
	})

	if err != nil {
		return err
	}

	var unreferenced []string
	for m, used := range macros {
		if !used {
			unreferenced = append(unreferenced, m)
		}
	}

	if len(unreferenced) > 0 {
		sort.Strings(unreferenced)
		var errb strings.Builder
		errb.WriteString("\n======================================================================\n")
		errb.WriteString("FATAL ERROR: MANIFEST COMPILER FAIL-FAST TRIGGERED!\n")
		errb.WriteString("The following macros were generated but NEVER referenced in the C code:\n")
		for _, m := range unreferenced {
			errb.WriteString(fmt.Sprintf("  - %s\n", m))
		}
		errb.WriteString("=\nThis indicates a severe architectural gap! Either:\n")
		errb.WriteString("  1. The C code is using a hardcoded fallback and ignoring the manifest.\n")
		errb.WriteString("  2. The manifest is generating dead code that should be pruned.\n")
		errb.WriteString("Fix the C code to use these macros, or remove them from the generator.\n")
		errb.WriteString("======================================================================\n")
		return fmt.Errorf(errb.String())
	}

	fmt.Println("[Manifest Verifier] SUCCESS: All generated macros are perfectly synchronized with the C code!")
	return nil
}
