package manifest

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/toob-boot/toob/internal/ui"
)

type MapEntry struct {
	Name string
	Addr uint32
	Size uint32
	Type string
}

func GenerateHeadersAndScripts(dt *DeviceToml, hj *HardwareJson, cm *ChipManifest, drivers map[string]*DriverManifest, alloc *Allocator, outDir string,
	s0Addr, s0Budget, s1aAddr, s1bAddr, s1Budget, appAddr, stagingAddr, appBudget,
	recAddr, recBudget, netAddr, netBudget, scratchAddr, scratchSize, walAddr, walSize uint32,
	walAddrs []uint32, walSizes []uint32, kdmAddr, kdmBudget, cloudCmdAddr, cloudCmdBudget, mailboxAddr, mailboxBudget, forensicAddr, forensicBudget uint32) error {

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	flashSize := hj.Flash.Size
	maxSectorSize := alloc.maxSectorSize

	// Generate generated_boot_config.h
	headerPath := filepath.Join(outDir, "generated_boot_config.h")
	var b strings.Builder

	b.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	b.WriteString("#ifndef GENERATED_BOOT_CONFIG_H\n")
	b.WriteString("#define GENERATED_BOOT_CONFIG_H\n\n")
	b.WriteString("#include <stdint.h>\n\n")

	b.WriteString("/* ========================================================================\n")
	b.WriteString(" * PARTITION MAP (Auto-Generated by Manifest Compiler)\n")
	b.WriteString(" * ========================================================================\n")

	entries := []MapEntry{
		{"Stage 0", s0Addr, s0Budget, "BOOT"},
		{"Stage 1 Bank A", s1aAddr, s1Budget, "BOOT"},
		{"Stage 1 Bank B", s1bAddr, s1Budget, "BOOT"},
		{"App Slot", appAddr, appBudget, "APP"},
		{"Staging Slot", stagingAddr, appBudget, "APP"},
		{"Scratch / Delta Safe", scratchAddr, scratchSize, "SYSTEM"},
		{fmt.Sprintf("WAL Journal (%d sec)", dt.Partitions.WalSectors), walAddr, walSize, "SYSTEM"},
		{"KDM Quorum", kdmAddr, kdmBudget, "SYSTEM"},
		{"Cloud Command", cloudCmdAddr, cloudCmdBudget, "SYSTEM"},
		{"Mailbox", mailboxAddr, mailboxBudget, "SYSTEM"},
		{"Forensic Slot", forensicAddr, forensicBudget, "SYSTEM"},
	}
	if recBudget > 0 {
		entries = append(entries, MapEntry{"Recovery OS", recAddr, recBudget, "SYSTEM"})
	}
	if netBudget > 0 {
		entries = append(entries, MapEntry{"NetCore Slot", netAddr, netBudget, "APP"})
	}
	for _, r := range hj.Flash.Regions {
		if r.Type == "reserved" {
			name := r.Name
			if name == "" {
				name = "Hardware Reserved"
			}
			entries = append(entries, MapEntry{name, r.Base, r.Size, "RSVD"})
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Addr < entries[j].Addr
	})

	stats := map[string]uint32{"BOOT": 0, "SYSTEM": 0, "APP": 0, "RSVD": 0}
	for _, e := range entries {
		endAddr := e.Addr + e.Size
		stats[e.Type] += e.Size
		b.WriteString(fmt.Sprintf(" *   ├──────────────────────────────────────────────────┤ 0x%08X - 0x%08X\n", e.Addr, endAddr))
		b.WriteString(fmt.Sprintf(" *   │  [%-6s] %s (%d KB)\n", e.Type, e.Name, e.Size/1024))
	}

	b.WriteString(" *   └──────────────────────────────────────────────────┘ \n *\n")

	freeSpace := flashSize - alloc.CurrentOffset()
	b.WriteString(" * STORAGE SUMMARY:\n")
	b.WriteString(fmt.Sprintf(" *   Physical Flash Size:   %8d KB\n", flashSize/1024))
	b.WriteString(fmt.Sprintf(" *   Hardware Reserved:     %8d KB\n", stats["RSVD"]/1024))
	b.WriteString(fmt.Sprintf(" *   Bootloader Core:       %8d KB\n", stats["BOOT"]/1024))
	b.WriteString(fmt.Sprintf(" *   System & Scratch:      %8d KB\n", stats["SYSTEM"]/1024))
	b.WriteString(fmt.Sprintf(" *   Usable App Space:      %8d KB\n", stats["APP"]/1024))
	b.WriteString(fmt.Sprintf(" *   Unallocated / Free:    %8d KB\n", freeSpace/1024))
	b.WriteString(" * ======================================================================== */\n\n")

	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_WRITE_ALIGNMENT  %dU\n", hj.Flash.WriteAlignment))

	flashBase := hj.Flash.BaseAddr
	if flashBase == "" {
		flashBase = "0x00000000"
	}
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_BASE_ADDR        %sU\n\n", flashBase))

	stagingSlotID := dt.Partitions.StagingSlotID
	if stagingSlotID == 0 {
		stagingSlotID = 2
	}
	b.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_ID        %dU\n\n", stagingSlotID))

	walSectors := dt.Partitions.WalSectors
	if walSectors == 0 {
		walSectors = 4
	}
	b.WriteString(fmt.Sprintf("#define TOOB_WAL_SECTORS            %dU\n\n", walSectors))

	b.WriteString("#define TOOB_WAL_SECTOR_ADDRS { \\\n")
	for i, a := range walAddrs {
		comma := ","
		if i == len(walAddrs)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    0x%08XU%s \\\n", a, comma))
	}
	b.WriteString("}\n")

	b.WriteString("#define TOOB_WAL_SECTOR_SIZES { \\\n")
	for i, s := range walSizes {
		comma := ","
		if i == len(walSizes)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    %dU%s \\\n", s, comma))
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("#define BOOT_CRYPTO_ARENA_SIZE      %dU\n\n", hj.CryptoCapabilities.ArenaSize))

	wdtTimeout := dt.BootConfig.WdtTimeoutMs
	if wdtTimeout == 0 {
		wdtTimeout = 4100
	}
	b.WriteString(fmt.Sprintf("#define BOOT_WDT_TIMEOUT_MS         %dU\n\n", wdtTimeout))

	xipBase := hj.Flash.XipBase
	if xipBase == "" {
		xipBase = "0x0"
	}
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_XIP_BASE         %sU\n\n", xipBase))
	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_TOTAL_SIZE       0x%08XU\n", flashSize))

	b.WriteString(fmt.Sprintf("#define CHIP_FLASH_MAX_SECTOR_SIZE  %dU\n", maxSectorSize))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_MAX_RETRIES     %dU\n", dt.BootConfig.MaxRetries))
	b.WriteString(fmt.Sprintf("#define BOOT_CONFIG_MAX_RECOVERY_RETRIES %dU\n", dt.BootConfig.MaxRecoveryRetries))

	edgeMode := "0"
	if dt.BootConfig.EdgeUnattendedMode {
		edgeMode = "1"
	}
	fmt.Fprintf(&b, "#define BOOT_CONFIG_EDGE_UNATTENDED_MODE %s\n", edgeMode)
	fmt.Fprintf(&b, "#define BOOT_CONFIG_BACKOFF_BASE_S  %dU\n", dt.BootConfig.BackoffBaseS)
	b.WriteString(fmt.Sprintf("#define BOOT_STAGE1_SVN             %dU\n", dt.BootConfig.Stage1Svn))

	if dt.BootConfig.TransportProvider != "" {
		b.WriteString(fmt.Sprintf("#define TOOB_TRANSPORT_PROVIDER     TOOB_TRANSPORT_%s\n", strings.ToUpper(dt.BootConfig.TransportProvider)))
	}

	// P7d: Crypto-Backend Compile-Time Gating
	pqcEnabled := "0"
	if dt.Crypto.Pqc != "" {
		pqcEnabled = "1"
	}
	b.WriteString(fmt.Sprintf("#define TOOB_PQC_ENABLED            %s\n", pqcEnabled))
	if dt.Crypto.Backend != "" {
		b.WriteString(fmt.Sprintf("#define TOOB_CRYPTO_BACKEND         \"%s\"\n", dt.Crypto.Backend))
	}
	b.WriteString("\n")

	// Register Blocks (REG-031): base + per-register offset macros
	if len(hj.RegisterBlocks) > 0 {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * HARDWARE REGISTER BLOCKS (from hardware.json register_blocks)\n")
		b.WriteString(" * ======================================================================== */\n")
		var blockNames []string
		for name := range hj.RegisterBlocks {
			blockNames = append(blockNames, name)
		}
		sort.Strings(blockNames)
		for _, name := range blockNames {
			block := hj.RegisterBlocks[name]
			baseMacro := "CHIP_REG_" + strings.ToUpper(name) + "_BASE"
			b.WriteString(fmt.Sprintf("#define %-40s %sU\n", baseMacro, block.Base))

			var regNames []string
			for rn := range block.Regs {
				regNames = append(regNames, rn)
			}
			sort.Strings(regNames)
			for _, rn := range regNames {
				regMacro := "CHIP_REG_" + strings.ToUpper(name) + "_" + strings.ToUpper(rn)
				b.WriteString(fmt.Sprintf("#define %-40s (%s + %sU)\n", regMacro, baseMacro, block.Regs[rn]))
			}
			b.WriteString("\n")
		}
	}

	// Flat registers (REG-031): standalone addresses without block grouping
	if len(hj.RegistersFlat) > 0 {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * HARDWARE REGISTERS FLAT (from hardware.json registers_flat)\n")
		b.WriteString(" * ======================================================================== */\n")
		var flatKeys []string
		for k := range hj.RegistersFlat {
			flatKeys = append(flatKeys, k)
		}
		sort.Strings(flatKeys)
		for _, k := range flatKeys {
			macroName := "CHIP_REG_" + strings.ToUpper(k)
			b.WriteString(fmt.Sprintf("#define %-40s %sU\n", macroName, hj.RegistersFlat[k]))
		}
		b.WriteString("\n")
	}

	// Legacy flat registers fallback (deprecated — use register_blocks/registers_flat)
	if len(hj.RegisterBlocks) == 0 && len(hj.RegistersFlat) == 0 && len(hj.Registers) > 0 {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * HARDWARE REGISTERS (Dynamic from hardware.json)\n")
		b.WriteString(" * ======================================================================== */\n")
		var regKeys []string
		for k := range hj.Registers {
			regKeys = append(regKeys, k)
		}
		sort.Strings(regKeys)
		for _, k := range regKeys {
			macroName := "CHIP_REG_" + strings.ToUpper(k)
			v := hj.Registers[k]
			switch val := v.(type) {
			case string:
				b.WriteString(fmt.Sprintf("#define %-30s %sU\n", macroName, val))
			case float64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			}
		}
		b.WriteString("\n")
	}


	if len(hj.Constants) > 0 {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * CHIP CONSTANTS (Dynamic from hardware.json)\n")
		b.WriteString(" * ======================================================================== */\n")
		var constKeys []string
		for k := range hj.Constants {
			constKeys = append(constKeys, k)
		}
		sort.Strings(constKeys)
		for _, k := range constKeys {
			macroName := "CHIP_" + strings.ToUpper(k)
			v := hj.Constants[k]
			switch val := v.(type) {
			case string:
				b.WriteString(fmt.Sprintf("#define %-30s %sU\n", macroName, val))
			case float64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			}
		}
		b.WriteString("\n")
	}

	// Reset Causes (REG-031): structured codes + classification from hardware.json
	if hj.ResetCauses != nil && len(hj.ResetCauses.Codes) > 0 {
		rc := hj.ResetCauses
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * RESET CAUSE CONSTANTS (from hardware.json reset_causes)\n")
		b.WriteString(" * ======================================================================== */\n")
		fmt.Fprintf(&b, "#define %-40s %sU\n", "CHIP_RST_CAUSE_OFFSET", rc.RegisterOffset)
		fmt.Fprintf(&b, "#define %-40s %sU\n", "CHIP_RST_CAUSE_MASK", rc.Mask)
		for _, code := range rc.Codes {
			macroName := "CHIP_RST_" + strings.ToUpper(code.Name)
			b.WriteString(fmt.Sprintf("#define %-40s %dU\n", macroName, code.Value))
		}
		b.WriteString("\n/* ========================================================================\n")
		b.WriteString(" * WDT REGISTER & RESET ALIASES (REG-023)\n")
		b.WriteString(" * ======================================================================== */\n")
		b.WriteString("#define REG_TIMG0_WDT_CONFIG0      CHIP_REG_TIMG0_WDT_CONFIG0\n")
		b.WriteString("#define REG_TIMG0_WDT_FEED         CHIP_REG_TIMG0_WDT_FEED\n")
		b.WriteString("#define REG_TIMG0_WDT_WPROTECT     CHIP_REG_TIMG0_WDT_WPROTECT\n")
		b.WriteString("#define REG_TIMG1_WDT_CONFIG0      CHIP_REG_TIMG1_WDT_CONFIG0\n")
		b.WriteString("#define REG_TIMG1_WDT_WPROTECT     CHIP_REG_TIMG1_WDT_WPROTECT\n")
		b.WriteString("#define REG_LP_WDT_CONFIG0         CHIP_REG_LP_WDT_CONFIG0\n")
		b.WriteString("#define REG_LP_WDT_WPROTECT        CHIP_REG_LP_WDT_WPROTECT\n")
		b.WriteString("#define REG_LP_WDT_SWD_CONFIG      CHIP_REG_LP_WDT_SWD_CONFIG\n")
		b.WriteString("#define REG_LP_WDT_SWD_WPROTECT    CHIP_REG_LP_WDT_SWD_WPROTECT\n\n")
		b.WriteString("#define REG_RESET_CAUSE            (CHIP_REG_PMU_BASE + CHIP_RST_CAUSE_OFFSET)\n")
		b.WriteString("#define REG_RESET_CAUSE_MASK       CHIP_RST_CAUSE_MASK\n\n")
		b.WriteString("#define ADDR_CONFIRM_RTC_RAM       ((volatile uint64_t *)(uintptr_t)CHIP_REG_CONFIRM_STORAGE_BASE)\n")
	}

	if dt.DriverConfig != nil {

		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * USER DRIVER CONFIGURATION (Dynamic from device.toml)\n")
		b.WriteString(" * ======================================================================== */\n")
		var drvKeys []string
		for k := range dt.DriverConfig {
			drvKeys = append(drvKeys, k)
		}
		sort.Strings(drvKeys)
		for _, k := range drvKeys {
			macroName := "TOOB_DRIVER_" + strings.ToUpper(k)
			v := dt.DriverConfig[k]
			switch val := v.(type) {
			case string:
				b.WriteString(fmt.Sprintf("#define %-30s %s\n", macroName, val))
			case int64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			case float64:
				b.WriteString(fmt.Sprintf("#define %-30s %dU\n", macroName, uint32(val)))
			case bool:
				if val {
					b.WriteString(fmt.Sprintf("#define %-30s 1\n", macroName))
				} else {
					b.WriteString(fmt.Sprintf("#define %-30s 0\n", macroName))
				}
			}
		}
		b.WriteString("\n")
	}

	// Emit LP_RAM layout constants if declared
	if hj.Memory.LpRamBase != "" && hj.Memory.LpRamSize != "" {
		b.WriteString("/* ========================================================================\n")
		b.WriteString(" * LP_RAM LAYOUT (Low-Power SRAM, survives resets)\n")
		b.WriteString(" * ======================================================================== */\n")
		b.WriteString(fmt.Sprintf("#define %-30s %sU\n", "CHIP_LP_RAM_BASE", hj.Memory.LpRamBase))
		b.WriteString(fmt.Sprintf("#define %-30s %sU\n", "CHIP_LP_RAM_SIZE", hj.Memory.LpRamSize))
		b.WriteString("\n")
	}

	b.WriteString("#include \"boot_layout.h\"\n")
	b.WriteString("#include \"boot_layout_assert.h\"\n\n")

	b.WriteString("#endif /* GENERATED_BOOT_CONFIG_H */\n")

	if err := writeFileIfChanged(headerPath, []byte(b.String())); err != nil {
		return err
	}

	// Generate chip_config.h compatibility shim (REG-023)
	chipConfigPath := filepath.Join(outDir, "chip_config.h")
	var ccb strings.Builder
	ccb.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER — COMPATIBILITY SHIM */\n")
	ccb.WriteString("#ifndef CHIP_CONFIG_H\n")
	ccb.WriteString("#define CHIP_CONFIG_H\n\n")
	ccb.WriteString("#include \"generated_boot_config.h\"\n\n")
	ccb.WriteString("#endif /* CHIP_CONFIG_H */\n")
	if err := writeFileIfChanged(chipConfigPath, []byte(ccb.String())); err != nil {
		return err
	}

	// Generate generated_reset_causes.h (REG-031)
	if hj.ResetCauses != nil && len(hj.ResetCauses.Codes) > 0 {
		rcPath := filepath.Join(outDir, "generated_reset_causes.h")
		var rcb strings.Builder
		rcb.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER — DO NOT EDIT */\n")
		rcb.WriteString("#ifndef GENERATED_RESET_CAUSES_H\n")
		rcb.WriteString("#define GENERATED_RESET_CAUSES_H\n\n")
		rcb.WriteString("#include <stdint.h>\n\n")

		rcb.WriteString("#define CHIP_RST_CLASS_UNKNOWN     0U\n")
		rcb.WriteString("#define CHIP_RST_CLASS_POWER       1U\n")
		rcb.WriteString("#define CHIP_RST_CLASS_INTENTIONAL 2U\n")
		rcb.WriteString("#define CHIP_RST_CLASS_CRASH       3U\n\n")

		rcb.WriteString("typedef struct {\n")
		rcb.WriteString("    uint8_t hw_code;\n")
		rcb.WriteString("    uint8_t rst_class;\n")
		rcb.WriteString("} chip_reset_cause_entry_t;\n\n")

		rcb.WriteString("static const chip_reset_cause_entry_t CHIP_RESET_CAUSE_TABLE[] = {\n")
		for _, code := range hj.ResetCauses.Codes {
			classConst := "CHIP_RST_CLASS_UNKNOWN"
			switch code.Class {
			case "power":
				classConst = "CHIP_RST_CLASS_POWER"
			case "intentional":
				classConst = "CHIP_RST_CLASS_INTENTIONAL"
			case "crash":
				classConst = "CHIP_RST_CLASS_CRASH"
			}
			rcb.WriteString(fmt.Sprintf("    { %2d, %-28s }, /* %s */\n", code.Value, classConst, code.Name))
		}
		rcb.WriteString("};\n")
		rcb.WriteString(fmt.Sprintf("#define CHIP_RESET_CAUSE_TABLE_LEN %d\n\n", len(hj.ResetCauses.Codes)))

		rcb.WriteString("/**\n")
		rcb.WriteString(" * @brief Lookup reset class for a hardware reset code.\n")
		rcb.WriteString(" * @return CHIP_RST_CLASS_* constant.\n")
		rcb.WriteString(" */\n")
		rcb.WriteString("static inline uint8_t chip_rst_class_lookup(uint8_t hw_code)\n")
		rcb.WriteString("{\n")
		rcb.WriteString("    for (uint8_t i = 0; i < CHIP_RESET_CAUSE_TABLE_LEN; i++) {\n")
		rcb.WriteString("        if (CHIP_RESET_CAUSE_TABLE[i].hw_code == hw_code) {\n")
		rcb.WriteString("            return CHIP_RESET_CAUSE_TABLE[i].rst_class;\n")
		rcb.WriteString("        }\n")
		rcb.WriteString("    }\n")
		rcb.WriteString("    return CHIP_RST_CLASS_UNKNOWN;\n")
		rcb.WriteString("}\n\n")

		rcb.WriteString("#endif /* GENERATED_RESET_CAUSES_H */\n")

		if err := writeFileIfChanged(rcPath, []byte(rcb.String())); err != nil {
			return err
		}
	}

	// Generate boot_layout.h

	layoutPath := filepath.Join(outDir, "boot_layout.h")
	var lob strings.Builder
	lob.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER — DO NOT EDIT */\n")
	lob.WriteString("#ifndef BOOT_LAYOUT_H\n")
	lob.WriteString("#define BOOT_LAYOUT_H\n\n")

	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE0_ABS_ADDR         0x%08XU\n", s0Addr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE0_SIZE             0x%08XU\n", s0Budget))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1A_ABS_ADDR        0x%08XU\n", s1aAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1A_SIZE            0x%08XU\n", s1Budget))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1B_ABS_ADDR        0x%08XU\n", s1bAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGE1B_SIZE            0x%08XU\n\n", s1Budget))

	lob.WriteString(fmt.Sprintf("#define CHIP_APP_SLOT_ABS_ADDR       0x%08XU\n", appAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_APP_SLOT_SIZE           0x%08XU\n", appBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_ABS_ADDR   0x%08XU\n", stagingAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_STAGING_SLOT_SIZE       0x%08XU\n\n", appBudget))

	lob.WriteString(fmt.Sprintf("#define CHIP_SCRATCH_SLOT_ABS_ADDR   0x%08XU\n", scratchAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_SCRATCH_SLOT_SIZE       0x%08XU\n\n", scratchSize))

	lob.WriteString(fmt.Sprintf("#define CHIP_WAL_ABS_ADDR            0x%08XU\n", walAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_WAL_SIZE                0x%08XU\n\n", walSize))

	for i, a := range walAddrs {
		lob.WriteString(fmt.Sprintf("#define CHIP_WAL_SECTOR_%d_ADDR       0x%08XU\n", i, a))
		lob.WriteString(fmt.Sprintf("#define CHIP_WAL_SECTOR_%d_SIZE       0x%08XU\n", i, walSizes[i]))
	}
	lob.WriteString("\n")

	lob.WriteString(fmt.Sprintf("#define CHIP_RECOVERY_OS_ABS_ADDR    0x%08XU\n", recAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_RECOVERY_OS_SIZE        0x%08XU\n", recBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_NETCORE_SLOT_ABS_ADDR   0x%08XU\n", netAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_NETCORE_SLOT_SIZE       0x%08XU\n\n", netBudget))

	lob.WriteString(fmt.Sprintf("#define CHIP_KDM_QUORUM_ABS_ADDR     0x%08XU\n", kdmAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_KDM_QUORUM_SIZE         0x%08XU\n", kdmBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_CLOUD_CMD_SLOT_ABS_ADDR 0x%08XU\n", cloudCmdAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_CLOUD_CMD_SLOT_SIZE     0x%08XU\n\n", cloudCmdBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_MAILBOX_ABS_ADDR        0x%08XU\n", mailboxAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_MAILBOX_SLOT_SIZE       0x%08XU\n", mailboxBudget/2))
	lob.WriteString(fmt.Sprintf("#define CHIP_MAILBOX_SIZE            0x%08XU\n\n", mailboxBudget))
	lob.WriteString(fmt.Sprintf("#define CHIP_FORENSIC_SLOT_ABS_ADDR  0x%08XU\n", forensicAddr))
	lob.WriteString(fmt.Sprintf("#define CHIP_FORENSIC_SLOT_SIZE      0x%08XU\n\n", forensicBudget))



	lob.WriteString("#endif /* BOOT_LAYOUT_H */\n")

	if err := writeFileIfChanged(layoutPath, []byte(lob.String())); err != nil {
		return err
	}

	// Generate boot_layout_assert.h
	assertPath := filepath.Join(outDir, "boot_layout_assert.h")
	var aob strings.Builder
	aob.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER — DO NOT EDIT */\n")
	aob.WriteString("#ifndef BOOT_LAYOUT_ASSERT_H\n")
	aob.WriteString("#define BOOT_LAYOUT_ASSERT_H\n\n")
	aob.WriteString("#include \"boot_layout.h\"\n\n")

	aob.WriteString("/* Helper macro to assert two regions do not overlap (if size > 0) */\n")
	aob.WriteString("#define BOOT_CHECK_DISJOINT(a_base, a_size, b_base, b_size) \\\n")
	aob.WriteString("    ( ((a_size) == 0) || ((b_size) == 0) || \\\n")
	aob.WriteString("      ((a_base) + (a_size) <= (b_base)) || ((b_base) + (b_size) <= (a_base)) )\n\n")

	type RegMeta struct {
		Name string
		Base string
		Size string
	}
	regMetas := []RegMeta{
		{"Stage 0", "CHIP_STAGE0_ABS_ADDR", "CHIP_STAGE0_SIZE"},
		{"Stage 1 Bank A", "CHIP_STAGE1A_ABS_ADDR", "CHIP_STAGE1A_SIZE"},
		{"Stage 1 Bank B", "CHIP_STAGE1B_ABS_ADDR", "CHIP_STAGE1B_SIZE"},
		{"App Slot", "CHIP_APP_SLOT_ABS_ADDR", "CHIP_APP_SLOT_SIZE"},
		{"Staging Slot", "CHIP_STAGING_SLOT_ABS_ADDR", "CHIP_STAGING_SLOT_SIZE"},
		{"Scratch Slot", "CHIP_SCRATCH_SLOT_ABS_ADDR", "CHIP_SCRATCH_SLOT_SIZE"},
		{"WAL Journal", "CHIP_WAL_ABS_ADDR", "CHIP_WAL_SIZE"},
		{"Recovery OS", "CHIP_RECOVERY_OS_ABS_ADDR", "CHIP_RECOVERY_OS_SIZE"},
		{"NetCore Slot", "CHIP_NETCORE_SLOT_ABS_ADDR", "CHIP_NETCORE_SLOT_SIZE"},
		{"KDM Quorum", "CHIP_KDM_QUORUM_ABS_ADDR", "CHIP_KDM_QUORUM_SIZE"},
		{"Cloud Command", "CHIP_CLOUD_CMD_SLOT_ABS_ADDR", "CHIP_CLOUD_CMD_SLOT_SIZE"},
		{"Mailbox", "CHIP_MAILBOX_ABS_ADDR", "CHIP_MAILBOX_SIZE"},
		{"Forensic Slot", "CHIP_FORENSIC_SLOT_ABS_ADDR", "CHIP_FORENSIC_SLOT_SIZE"},
	}

	aob.WriteString("/* 1. Pairwise Disjointness (Overlap-Free) Assertions */\n")
	for i := 0; i < len(regMetas); i++ {
		for j := i + 1; j < len(regMetas); j++ {
			aob.WriteString(fmt.Sprintf("_Static_assert(BOOT_CHECK_DISJOINT(%s, %s, %s, %s),\n",
				regMetas[i].Base, regMetas[i].Size, regMetas[j].Base, regMetas[j].Size))
			aob.WriteString(fmt.Sprintf("               \"Layout Overlap: %s and %s overlap!\");\n",
				regMetas[i].Name, regMetas[j].Name))
		}
	}
	aob.WriteString("\n")

	aob.WriteString("/* 2. Sector Alignment Assertions (Base address must be a multiple of sector size) */\n")
	for _, r := range regMetas {
		aob.WriteString(fmt.Sprintf("_Static_assert(%s == 0 || (%s %% CHIP_FLASH_MAX_SECTOR_SIZE) == 0,\n", r.Size, r.Base))
		aob.WriteString(fmt.Sprintf("               \"Layout Alignment: %s is not aligned to CHIP_FLASH_MAX_SECTOR_SIZE!\");\n", r.Name))
	}
	aob.WriteString("\n")

	aob.WriteString("/* 3. Minimum Size Assertions */\n")
	aob.WriteString("_Static_assert(TOOB_WAL_SECTORS >= 4,\n")
	aob.WriteString("               \"WAL minimum size: TOOB_WAL_SECTORS must be >= 4!\");\n")
	for i := range walAddrs {
		aob.WriteString(fmt.Sprintf("_Static_assert(CHIP_WAL_SECTOR_%d_SIZE >= 128,\n", i))
		aob.WriteString(fmt.Sprintf("               \"WAL sector %d minimum size: must be >= 128 bytes (Header+Entry)!\");\n", i))
	}
	aob.WriteString("_Static_assert(CHIP_SCRATCH_SLOT_SIZE == 0 || CHIP_SCRATCH_SLOT_SIZE >= CHIP_FLASH_MAX_SECTOR_SIZE,\n")
	aob.WriteString("               \"Scratch Slot minimum size: must be >= CHIP_FLASH_MAX_SECTOR_SIZE!\");\n")
	aob.WriteString("_Static_assert(CHIP_KDM_QUORUM_SIZE >= 3 * CHIP_FLASH_MAX_SECTOR_SIZE,\n")
	aob.WriteString("               \"KDM Quorum minimum size: must be >= 3 sectors for Phase 4 quorum!\");\n\n")

	aob.WriteString("/* 4. Wrap-Around / Overflow Protection */\n")
	for _, r := range regMetas {
		aob.WriteString(fmt.Sprintf("_Static_assert(%s + %s >= %s,\n", r.Base, r.Size, r.Base))
		aob.WriteString(fmt.Sprintf("               \"Layout Overflow: %s address range wraps around!\");\n", r.Name))
	}
	aob.WriteString("\n")

	aob.WriteString("#endif /* BOOT_LAYOUT_ASSERT_H */\n")

	if err := writeFileIfChanged(assertPath, []byte(aob.String())); err != nil {
		return err
	}

	// Generate generated_memory.ld
	ldPath := filepath.Join(outDir, "generated_memory.ld")
	var ldb strings.Builder
	ldb.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	ldb.WriteString(fmt.Sprintf("__S0_BUDGET_START = 0x%08X;\n", s0Addr))
	fmt.Fprintf(&ldb, "__S0_BUDGET_SIZE = 0x%08X;\n", s0Budget)
	ldb.WriteString(fmt.Sprintf("__S1A_BUDGET_START = 0x%08X;\n", s1aAddr))
	ldb.WriteString(fmt.Sprintf("__S1B_BUDGET_START = 0x%08X;\n", s1bAddr))
	ldb.WriteString(fmt.Sprintf("__S1_BUDGET_SIZE = 0x%08X;\n", s1Budget))
	ldb.WriteString(fmt.Sprintf("__APP_BUDGET_START = 0x%08X;\n", appAddr))
	ldb.WriteString(fmt.Sprintf("__APP_BUDGET_SIZE = 0x%08X;\n", appBudget))
	if err := writeFileIfChanged(ldPath, []byte(ldb.String())); err != nil {
		return err
	}

	// Generate stage0_layout.ld
	stage0LdPath := filepath.Join(outDir, "stage0_layout.ld")
	var s0ld strings.Builder
	s0ld.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	s0ld.WriteString("/* Valid Stage 0 Layout */\n")
	s0ld.WriteString("ENTRY(main)\n\n")
	s0ld.WriteString("INCLUDE generated_memory.ld\n\n")
	s0ld.WriteString("MEMORY {\n")
	s0ld.WriteString(fmt.Sprintf("    S0_RAM (rwx) : ORIGIN = %s, LENGTH = %s\n", hj.Memory.IramBase, hj.Memory.IramSize))
	s0ld.WriteString("    S0_ROM (rx)  : ORIGIN = __S0_BUDGET_START, LENGTH = __S0_BUDGET_SIZE\n")
	s0ld.WriteString("}\n\n")
	s0ld.WriteString("SECTIONS {\n")
	s0ld.WriteString("    .text : {\n")
	s0ld.WriteString("        KEEP(*(.text.main))\n")
	s0ld.WriteString("        *(.text .text.*)\n")
	s0ld.WriteString("    } > S0_ROM\n\n")
	s0ld.WriteString("    .rodata : {\n")
	s0ld.WriteString("        *(.rodata .rodata.*)\n")
	s0ld.WriteString("        *(.srodata .srodata.*)\n")
	s0ld.WriteString("    } > S0_ROM\n\n")
	s0ld.WriteString("    .data : {\n")
	s0ld.WriteString("        *(.data .data.*)\n")
	s0ld.WriteString("        *(.sdata .sdata.*)\n")
	s0ld.WriteString("    } > S0_RAM AT > S0_ROM\n\n")
	s0ld.WriteString("    .bss (NOLOAD) : {\n")
	s0ld.WriteString("        *(.bss .bss.*)\n")
	s0ld.WriteString("        *(.sbss .sbss.*)\n")
	s0ld.WriteString("        *(COMMON)\n")
	s0ld.WriteString("    } > S0_RAM\n\n")
	s0ld.WriteString("    .toob_mock_section : {\n")
	s0ld.WriteString("        KEEP(*(.toob_mock_section))\n")
	s0ld.WriteString("    } > S0_ROM\n")
	s0ld.WriteString("}\n")
	if err := writeFileIfChanged(stage0LdPath, []byte(s0ld.String())); err != nil {
		return err
	}

	// Reserved RAM diagnostics (validation moved to provenance plausibility engine)
	for _, r := range hj.ReservedRamRegions {
		baseStr := strings.TrimPrefix(r.Base, "0x")
		baseStr = strings.TrimPrefix(baseStr, "0X")
		addr, err := strconv.ParseUint(baseStr, 16, 64)
		if err != nil {
			return fmt.Errorf("FATAL: reserved_ram_regions[%s]: invalid base address '%s': %w", r.Name, r.Base, err)
		}
		ui.Info("  Reserved RAM: %-20s at 0x%08X (%d bytes) — %s", r.Name, addr, r.Size, r.Description)
	}

	if err := GenerateProvenanceReport(hj, outDir); err != nil {
		return err
	}

	if err := generatePlatformWiring(cm, hj, drivers, outDir); err != nil {
		return fmt.Errorf("failed to generate platform wiring: %w", err)
	}

	return nil
}

func LoadDriverManifests(halRoot string, driverPaths []string) map[string]*DriverManifest {
	drivers := make(map[string]*DriverManifest)
	for _, relPath := range driverPaths {
		dir := filepath.Dir(relPath)
		manifestPath := filepath.Join(halRoot, dir, "driver_manifest.json")
		data, err := os.ReadFile(manifestPath)
		if err != nil {
			continue
		}
		var dm DriverManifest
		if err := json.Unmarshal(data, &dm); err == nil && dm.Trait != "" {
			drivers[dm.Trait] = &dm
		}
	}
	return drivers
}

func sanitizeSymbol(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ToLower(s)
	return s
}

func generatePlatformWiring(cm *ChipManifest, hj *HardwareJson, drivers map[string]*DriverManifest, outDir string) error {
	chipPrefix := "chip"
	if cm != nil && cm.Name != "" {
		chipPrefix = sanitizeSymbol(cm.Name)
	} else if hj != nil && hj.ChipFamily != "" {
		chipPrefix = sanitizeSymbol(hj.ChipFamily)
	}

	archHeader := "arch_riscv.h"
	archDisableInterrupts := "arch_riscv_disable_interrupts()"
	if cm != nil {
		switch strings.ToLower(cm.Arch) {
		case "arm", "armv7m", "cortex-m", "cortex_m":
			archHeader = "arch_arm.h"
			archDisableInterrupts = "arch_arm_disable_interrupts()"
		case "riscv32", "riscv", "riscv64":
			archHeader = "arch_riscv.h"
			archDisableInterrupts = "arch_riscv_disable_interrupts()"
		case "xtensa":
			archHeader = "arch_xtensa.h"
			archDisableInterrupts = "arch_xtensa_disable_interrupts()"
		}
	}

	sym := func(trait, key, fallback string) string {
		if drivers != nil {
			if dm, ok := drivers[trait]; ok && dm.Symbols != nil {
				if s, found := dm.Symbols[key]; found && s != "" {
					return s
				}
			}
		}
		return fallback
	}

	flashInit := sym("flash", "init", "esp_flash_init")
	flashDeinit := sym("flash", "deinit", "esp_flash_deinit")
	flashRead := sym("flash", "read", "esp_flash_read")
	flashWrite := sym("flash", "write", "esp_flash_write")
	flashErase := sym("flash", "erase_sector", "esp_flash_erase_sector")
	flashGetSector := sym("flash", "get_sector_size", "esp_flash_get_sector_size")
	flashGetErr := sym("flash", "get_vendor_error", "esp_flash_get_vendor_error")

	confirmInit := sym("confirm", "init", "esp_confirm_init")
	confirmDeinit := sym("confirm", "deinit", "esp_confirm_deinit")
	confirmCheck := sym("confirm", "check_ok", "esp_confirm_check_ok")
	confirmClear := sym("confirm", "clear", "esp_confirm_clear")

	wdtInit := sym("wdt", "init", "esp_rwdt_init")
	wdtDeinit := sym("wdt", "deinit", "esp_rwdt_deinit")
	wdtKick := sym("wdt", "kick", "esp_rwdt_kick")
	wdtSuspend := sym("wdt", "suspend", "esp_rwdt_suspend")
	wdtResume := sym("wdt", "resume", "esp_rwdt_resume")

	clockResetReason := sym("clock", "get_reset_reason", "esp_get_reset_reason")

	consoleInit := sym("console", "init", "esp_uart_init")
	consoleDeinit := sym("console", "deinit", "esp_uart_deinit")
	consolePutchar := sym("console", "putchar", "esp_uart_putchar")
	consoleGetchar := sym("console", "getchar", "esp_uart_getchar")
	consoleFlush := sym("console", "flush", "esp_uart_flush")

	slotCapsSymbol := "NULL"
	if drivers != nil {
		if slotDm, ok := drivers["slot_caps"]; ok && slotDm.Symbols != nil {
			if s, found := slotDm.Symbols["slot_caps"]; found && s != "" {
				slotCapsSymbol = "&" + s
			}
		}
	}

	var b strings.Builder
	b.WriteString("/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */\n")
	b.WriteString("#include \"boot_hal.h\"\n")
	b.WriteString("#include \"boot_panic.h\"\n")
	b.WriteString("#include \"boot_platform_bringup.h\"\n")
	b.WriteString("#include \"generated_boot_config.h\"\n\n")

	b.WriteString(fmt.Sprintf("#include \"%s\"\n", archHeader))
	b.WriteString("#include \"esp_common.h\"\n")
	b.WriteString("#include \"efuse.h\"\n")

	if drivers != nil {
		if slotDm, ok := drivers["slot_caps"]; ok {
			for _, h := range slotDm.Headers {
				b.WriteString(fmt.Sprintf("#include \"%s\"\n", h))
			}
		}
	}
	b.WriteString("\n#include <stddef.h>\n\n")

	b.WriteString("/* Vendor Driver Declarations */\n")
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(void);\n", flashInit))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n", flashDeinit))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint32_t addr, void *buf, size_t len);\n", flashRead))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint32_t addr, const void *buf, size_t len);\n", flashWrite))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint32_t addr);\n", flashErase))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint32_t addr, size_t *size_out);\n", flashGetSector))
	b.WriteString(fmt.Sprintf("extern uint32_t %s(void);\n\n", flashGetErr))

	b.WriteString(fmt.Sprintf("extern boot_status_t %s(void);\n", confirmInit))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n", confirmDeinit))
	b.WriteString(fmt.Sprintf("extern bool %s(uint64_t expected_nonce);\n", confirmCheck))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(void);\n\n", confirmClear))

	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint32_t timeout_ms);\n", wdtInit))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n", wdtDeinit))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n", wdtKick))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n", wdtSuspend))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n\n", wdtResume))

	b.WriteString(fmt.Sprintf("extern reset_reason_t %s(void);\n\n", clockResetReason))

	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint32_t baudrate);\n", consoleInit))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n", consoleDeinit))
	b.WriteString(fmt.Sprintf("extern void %s(char c);\n", consolePutchar))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s(uint8_t *out, uint32_t timeout_ms);\n", consoleGetchar))
	b.WriteString(fmt.Sprintf("extern void %s(void);\n\n", consoleFlush))

	b.WriteString(fmt.Sprintf("extern boot_status_t %s_read_pubkey(uint8_t *out_pubkey, size_t len, uint8_t key_index);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_read_dslc(uint8_t *out_dslc, size_t *len);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_write_dslc(const uint8_t *dslc, size_t len);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_read_monotonic(uint32_t *out_counter);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_advance_monotonic(void);\n\n", chipPrefix))

	b.WriteString(fmt.Sprintf("extern boot_status_t %s_burn_pubkey(const uint8_t *pubkey, size_t len, uint8_t index);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_prov_write_dslc(uint8_t dslc);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_set_protection_bits(uint32_t mask);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_enable_secure_boot(void);\n", chipPrefix))
	b.WriteString(fmt.Sprintf("extern boot_status_t %s_enable_flash_encryption(void);\n\n", chipPrefix))

	b.WriteString("/* Trait Struct Instantiations */\n")
	b.WriteString("static const flash_hal_t g_platform_flash_hal =\n")
	b.WriteString("    TOOB_FLASH_HAL_V2(\n")
	b.WriteString(fmt.Sprintf("        %s,\n", flashInit))
	b.WriteString(fmt.Sprintf("        %s,\n", flashDeinit))
	b.WriteString(fmt.Sprintf("        %s,\n", flashRead))
	b.WriteString(fmt.Sprintf("        %s,\n", flashWrite))
	b.WriteString(fmt.Sprintf("        %s,\n", flashErase))
	b.WriteString(fmt.Sprintf("        %s,\n", flashGetSector))
	b.WriteString(fmt.Sprintf("        .get_last_vendor_error = %s,\n", flashGetErr))
	b.WriteString("        .max_sector_size      = CHIP_FLASH_MAX_SECTOR_SIZE,\n")
	b.WriteString("        .total_size           = CHIP_FLASH_TOTAL_SIZE,\n")
	b.WriteString("        .max_erase_cycles     = 100000U,\n")
	b.WriteString("        .write_align          = CHIP_FLASH_WRITE_ALIGNMENT,\n")
	b.WriteString("        .erased_value         = CHIP_FLASH_ERASED_BYTE,\n")
	b.WriteString("        .erase_time_us_max    = 40000U,\n")
	b.WriteString("        .write_time_us_page   = 800U\n")
	b.WriteString("    );\n\n")

	b.WriteString("static const confirm_hal_t g_platform_confirm_hal =\n")
	b.WriteString("    TOOB_CONFIRM_HAL_V2(\n")
	b.WriteString(fmt.Sprintf("        %s,\n", confirmInit))
	b.WriteString(fmt.Sprintf("        %s,\n", confirmDeinit))
	b.WriteString(fmt.Sprintf("        %s,\n", confirmCheck))
	b.WriteString(fmt.Sprintf("        %s\n", confirmClear))
	b.WriteString("    );\n\n")

	b.WriteString("static const wdt_hal_t g_platform_wdt_hal =\n")
	b.WriteString("    TOOB_WDT_HAL_V2(\n")
	b.WriteString(fmt.Sprintf("        %s,\n", wdtInit))
	b.WriteString(fmt.Sprintf("        %s,\n", wdtDeinit))
	b.WriteString(fmt.Sprintf("        %s,\n", wdtKick))
	b.WriteString(fmt.Sprintf("        %s,\n", wdtSuspend))
	b.WriteString(fmt.Sprintf("        %s\n", wdtResume))
	b.WriteString("    );\n\n")

	b.WriteString("static boot_status_t g_clock_init_wrapper(void) {\n")
	b.WriteString("    arch_riscv_timer_init(CHIP_REG_SYSTIMER_BASE, CHIP_CPU_FREQ_HZ);\n")
	b.WriteString("    return BOOT_OK;\n")
	b.WriteString("}\n\n")

	b.WriteString("static void g_clock_deinit_wrapper(void) {\n")
	b.WriteString("}\n\n")

	b.WriteString("static const clock_hal_t g_platform_clock_hal =\n")
	b.WriteString("    TOOB_CLOCK_HAL_V2(\n")
	b.WriteString("        g_clock_init_wrapper,\n")
	b.WriteString("        g_clock_deinit_wrapper,\n")
	b.WriteString("        arch_riscv_get_tick_ms,\n")
	b.WriteString("        arch_riscv_delay_ms,\n")
	b.WriteString(fmt.Sprintf("        %s\n", clockResetReason))
	b.WriteString("    );\n\n")

	b.WriteString("static boot_status_t g_console_init_wrapper(uint32_t baudrate) {\n")
	b.WriteString(fmt.Sprintf("    return %s(baudrate);\n", consoleInit))
	b.WriteString("}\n\n")

	b.WriteString("static const console_hal_t g_platform_console_hal =\n")
	b.WriteString("    TOOB_CONSOLE_HAL_V2(\n")
	b.WriteString("        g_console_init_wrapper,\n")
	b.WriteString(fmt.Sprintf("        %s,\n", consoleDeinit))
	b.WriteString(fmt.Sprintf("        %s,\n", consolePutchar))
	b.WriteString(fmt.Sprintf("        %s,\n", consoleGetchar))
	b.WriteString(fmt.Sprintf("        %s\n", consoleFlush))
	b.WriteString("    );\n\n")

	b.WriteString("#define RNG_INTER_READ_CYCLES 160U\n\n")
	b.WriteString("static inline uint32_t rng_get_cycle_count(void)\n")
	b.WriteString("{\n")
	b.WriteString("    uint32_t cycles;\n")
	b.WriteString("    __asm__ volatile(\"csrr %0, mcycle\" : \"=r\"(cycles));\n")
	b.WriteString("    return cycles;\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("static boot_status_t %s_hw_random(uint8_t *buf, size_t len)\n", chipPrefix))
	b.WriteString("{\n")
	b.WriteString("    if (!buf || len == 0) {\n")
	b.WriteString("        return BOOT_ERR_INVALID_ARG;\n")
	b.WriteString("    }\n")
	b.WriteString("    uint32_t last_read_cycle = rng_get_cycle_count();\n")
	b.WriteString("    size_t pos = 0;\n")
	b.WriteString("    while (pos < len) {\n")
	b.WriteString("        while ((rng_get_cycle_count() - last_read_cycle) < RNG_INTER_READ_CYCLES) {\n")
	b.WriteString("        }\n")
	b.WriteString("        uint32_t word = REG_READ(CHIP_REG_RNG_DATA_REG);\n")
	b.WriteString("        last_read_cycle = rng_get_cycle_count();\n")
	b.WriteString("        size_t remaining = len - pos;\n")
	b.WriteString("        size_t chunk = (remaining >= 4U) ? 4U : remaining;\n")
	b.WriteString("        for (size_t i = 0; i < chunk; i++) {\n")
	b.WriteString("            buf[pos + i] = (uint8_t)(word >> (i * 8U));\n")
	b.WriteString("        }\n")
	b.WriteString("        pos += chunk;\n")
	b.WriteString("    }\n")
	b.WriteString("    return BOOT_OK;\n")
	b.WriteString("}\n\n")

	b.WriteString("static const crypto_hal_t g_platform_crypto_hal =\n")
	b.WriteString("    TOOB_CRYPTO_HAL_V2(\n")
	b.WriteString("        toob_crypto_hal_init,\n")
	b.WriteString("        toob_crypto_hal_deinit,\n")
	b.WriteString("        toob_crypto_hal_hash_init,\n")
	b.WriteString("        toob_crypto_hal_hash_update,\n")
	b.WriteString("        toob_crypto_hal_hash_finish,\n")
	b.WriteString("        toob_crypto_hal_verify_signature,\n")
	b.WriteString(fmt.Sprintf("        %s_hw_random,\n", chipPrefix))
	b.WriteString("        toob_crypto_hal_get_hash_ctx_size,\n")
	b.WriteString("        .verify_pqc               = toob_crypto_hal_verify_pqc,\n")
	b.WriteString(fmt.Sprintf("        .read_pubkey              = %s_read_pubkey,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .read_dslc                = %s_read_dslc,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .write_dslc               = %s_write_dslc,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .read_monotonic_counter   = %s_read_monotonic,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .advance_monotonic_counter = %s_advance_monotonic,\n", chipPrefix))
	b.WriteString("        .is_pqc_enforced          = toob_crypto_hal_is_pqc_enforced,\n")
	b.WriteString("        .verify_signature_ph      = toob_crypto_hal_verify_signature_ph\n")
	b.WriteString("    );\n\n")

	b.WriteString("static const provisioning_hal_t g_platform_provisioning_hal = {\n")
	b.WriteString(fmt.Sprintf("    .burn_pubkey          = %s_burn_pubkey,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("    .write_dslc           = %s_prov_write_dslc,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("    .set_protection_bits  = %s_set_protection_bits,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("    .enable_secure_boot   = %s_enable_secure_boot,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("    .enable_flash_encryption = %s_enable_flash_encryption,\n", chipPrefix))
	b.WriteString("};\n\n")

	b.WriteString("static const entropy_hal_t g_platform_entropy_hal =\n")
	b.WriteString("    TOOB_ENTROPY_HAL_V3(\n")
	b.WriteString(fmt.Sprintf("        NULL, NULL, %s_hw_random, .is_hardware_trng = true\n", chipPrefix))
	b.WriteString("    );\n\n")

	b.WriteString("static const keystore_hal_t g_platform_keystore_hal =\n")
	b.WriteString("    TOOB_KEYSTORE_HAL_V3(\n")
	b.WriteString(fmt.Sprintf("        NULL, NULL, %s_read_pubkey, %s_read_dslc, %s_write_dslc,\n", chipPrefix, chipPrefix, chipPrefix))
	b.WriteString(fmt.Sprintf("        .read_monotonic_counter = %s_read_monotonic,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .advance_monotonic_counter = %s_advance_monotonic,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .burn_pubkey = %s_burn_pubkey,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .set_protection_bits = %s_set_protection_bits,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .enable_secure_boot = %s_enable_secure_boot,\n", chipPrefix))
	b.WriteString(fmt.Sprintf("        .enable_flash_encryption = %s_enable_flash_encryption\n", chipPrefix))
	b.WriteString("    );\n\n")

	b.WriteString("static const boot_platform_t g_platform_instance = {\n")
	b.WriteString("    .flash        = &g_platform_flash_hal,\n")
	b.WriteString("    .confirm      = &g_platform_confirm_hal,\n")
	b.WriteString("    .crypto       = &g_platform_crypto_hal,\n")
	b.WriteString("    .clock        = &g_platform_clock_hal,\n")
	b.WriteString("    .wdt          = &g_platform_wdt_hal,\n")
	b.WriteString("    .console      = &g_platform_console_hal,\n")
	b.WriteString("    .soc          = NULL,\n")
	b.WriteString("    .provisioning = &g_platform_provisioning_hal,\n")
	b.WriteString(fmt.Sprintf("    .slot_caps    = %s,\n", slotCapsSymbol))
	b.WriteString("    .entropy      = &g_platform_entropy_hal,\n")
	b.WriteString("    .keystore     = &g_platform_keystore_hal,\n")
	b.WriteString("};\n\n")

	b.WriteString("static const bringup_step_t g_bringup_steps[] = {\n")
	b.WriteString("    { BOOT_HAL_KIND_CLOCK,   true,  SITE_BRINGUP_CLOCK },\n")
	b.WriteString("    { BOOT_HAL_KIND_FLASH,   true,  SITE_BRINGUP_FLASH },\n")
	b.WriteString("    { BOOT_HAL_KIND_WDT,     true,  SITE_BRINGUP_WDT },\n")
	b.WriteString("    { BOOT_HAL_KIND_CRYPTO,  true,  SITE_BRINGUP_CRYPTO },\n")
	b.WriteString("    { BOOT_HAL_KIND_CONFIRM, true,  SITE_BRINGUP_CONFIRM },\n")
	b.WriteString("    { BOOT_HAL_KIND_CONSOLE, false, 0 },\n")
	b.WriteString("};\n\n")

	b.WriteString("const boot_platform_t *boot_platform_init(void)\n")
	b.WriteString("{\n")
	b.WriteString(fmt.Sprintf("    %s;\n", archDisableInterrupts))
	b.WriteString("    (void)boot_platform_bringup(&g_platform_instance, g_bringup_steps,\n")
	b.WriteString("                                sizeof(g_bringup_steps) / sizeof(g_bringup_steps[0]));\n")
	b.WriteString("    return &g_platform_instance;\n")
	b.WriteString("}\n")

	cPath := filepath.Join(outDir, "generated_platform_wiring.c")
	incPath := filepath.Join(outDir, "generated_platform_wiring.inc")
	if err := writeFileIfChanged(incPath, []byte(b.String())); err != nil {
		return err
	}
	return writeFileIfChanged(cPath, []byte(b.String()))
}

func writeFileIfChanged(path string, data []byte) error {
	if old, err := os.ReadFile(path); err == nil && string(old) == string(data) {
		return nil
	}
	return os.WriteFile(path, data, 0o644)
}

func VerifyMacroUsage(headerPath, bootloaderDir, halChipDir string, extraDirs []string) error {
	ui.Step("Validating macro consumption in C code...")

	data, err := os.ReadFile(headerPath)
	if err != nil {
		return err
	}
	content := string(data)

	re := regexp.MustCompile(`#define\s+(CHIP_[A-Z0-9_]+|BOOT_[A-Z0-9_]+|TOOB_[A-Z0-9_]+)`)
	matches := re.FindAllStringSubmatch(content, -1)
	macros := make(map[string]bool)
	for _, m := range matches {
		if len(m) > 1 && m[1] != "GENERATED_BOOT_CONFIG_H" {
			macros[m[1]] = false // not used yet
		}
	}

	dirsToWalk := []string{bootloaderDir}
	if halChipDir != "" {
		dirsToWalk = append(dirsToWalk, halChipDir)
	}
	dirsToWalk = append(dirsToWalk, extraDirs...)

	var errAllFound = fmt.Errorf("all macros found")
	for _, dir := range dirsToWalk {
		walkErr := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return nil
			}
			if !d.IsDir() && (strings.HasSuffix(d.Name(), ".c") || strings.HasSuffix(d.Name(), ".h")) {
				b, err := os.ReadFile(path)
				if err == nil {
					text := string(b)
					allUsed := true
					for m, used := range macros {
						if !used {
							if strings.Contains(text, m) {
								macros[m] = true
							} else {
								allUsed = false
							}
						}
					}
					if allUsed {
						return errAllFound
					}
				}
			}
			return nil
		})
		if walkErr == errAllFound {
			break
		}
		if walkErr != nil {
			return walkErr
		}
	}

	var unreferenced []string
	for m, used := range macros {
		if !used {
			unreferenced = append(unreferenced, m)
		}
	}

	if len(unreferenced) > 0 {
		sort.Strings(unreferenced)
		var errb strings.Builder
		errb.WriteString("\n======================================================================\n")
		errb.WriteString("FATAL ERROR: MANIFEST COMPILER FAIL-FAST TRIGGERED!\n")
		errb.WriteString("The following macros were generated but NEVER referenced in the C code:\n")
		for _, m := range unreferenced {
			errb.WriteString(fmt.Sprintf("  - %s\n", m))
		}
		errb.WriteString("=\nThis indicates a severe architectural gap! Either:\n")
		errb.WriteString("  1. The C code is using a hardcoded fallback and ignoring the manifest.\n")
		errb.WriteString("  2. The manifest is generating dead code that should be pruned.\n")
		errb.WriteString("  3. You are developing/building locally and the registry sources in the cache (~/.toob/registry) are out of sync with your local registry. Ensure TOOB_REGISTRY_DIR points to your local registry directory!\n")
		errb.WriteString("Fix the C code to use these macros, or remove them from the generator.\n")
		errb.WriteString("======================================================================\n")
		return fmt.Errorf("%s", errb.String())
	}

	ui.Success("All generated macros are perfectly synchronized with the C code!")
	return nil
}
