"""Toob lockfile (``toob.lock``) parser and writer.

The lockfile guarantees reproducible builds by pinning the exact
registry commit and chip versions used by the project.

Format (TOML):
    [registry]
    commit = "a1b2c3d"

    [chips.esp32c6]
    version = "1.0.0"
    arch = "riscv32"
    vendor = "esp"
    spawned = false
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional


@dataclass
class ChipEntry:
    """State of a single installed chip."""

    version: str
    arch: str
    vendor: str
    spawned: bool = False


@dataclass
class Lockfile:
    """In-memory representation of ``toob.lock``."""

    registry_commit: str = ""
    chips: Dict[str, ChipEntry] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def add_chip(
        self,
        name: str,
        version: str,
        arch: str,
        vendor: str,
        spawned: bool,
    ) -> None:
        self.chips[name] = ChipEntry(
            version=version, arch=arch, vendor=vendor, spawned=spawned
        )

    def remove_chip(self, name: str) -> Optional[ChipEntry]:
        """Remove a chip entry. Returns the removed entry or None."""
        return self.chips.pop(name, None)

    def get_chip(self, name: str) -> Optional[ChipEntry]:
        return self.chips.get(name)

    def has_chip(self, name: str) -> bool:
        return name in self.chips

    def is_arch_shared(self, arch: str, exclude: str) -> bool:
        """Check if any chip other than *exclude* depends on *arch*."""
        return any(
            e.arch == arch for n, e in self.chips.items() if n != exclude
        )

    def is_vendor_shared(self, vendor: str, exclude: str) -> bool:
        """Check if any chip other than *exclude* depends on *vendor*."""
        return any(
            e.vendor == vendor for n, e in self.chips.items() if n != exclude
        )

    # ------------------------------------------------------------------
    # I/O
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, path: Path) -> Lockfile:
        """Parse an existing ``toob.lock`` file.

        Returns an empty Lockfile if the file does not exist.
        """
        if not path.is_file():
            return cls()

        raw = tomllib.loads(path.read_text(encoding="utf-8"))

        lf = cls()
        lf.registry_commit = raw.get("registry", {}).get("commit", "")

        for name, entry in raw.get("chips", {}).items():
            lf.chips[name] = ChipEntry(
                version=entry.get("version", "0.0.0"),
                arch=entry.get("arch", ""),
                vendor=entry.get("vendor", ""),
                spawned=entry.get("spawned", False),
            )
        return lf

    def save(self, path: Path) -> None:
        """Write the lockfile as TOML.

        Uses a hand-rolled serializer to avoid a ``tomli_w`` dependency.
        The structure is simple enough (flat tables, no arrays-of-tables)
        that a custom writer is safer than pulling in another package.
        """
        lines: list[str] = [
            "# Auto-generated by toob CLI. Do not edit manually.",
            "",
            "[registry]",
            f'commit = "{_escape(self.registry_commit)}"',
            "",
        ]

        for name in sorted(self.chips):
            entry = self.chips[name]
            lines.append(f"[chips.{name}]")
            lines.append(f'version = "{_escape(entry.version)}"')
            lines.append(f'arch = "{_escape(entry.arch)}"')
            lines.append(f'vendor = "{_escape(entry.vendor)}"')
            lines.append(f"spawned = {'true' if entry.spawned else 'false'}")
            lines.append("")

        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _escape(value: str) -> str:
    """Escape a string value for TOML (backslash + double-quote)."""
    return value.replace("\\", "\\\\").replace('"', '\\"')
