#include "fz_profiles.h"
#include "fz_types.h"

#include "logger.h"

// External prototypes
extern void fuzzer_scan(fz_profile_t profile);

// This is the universal entry point called by the `_startup.S` assembly after
// BSS init
int main(void) {
  // 1. Fetch AI-Generated Capabilities
  // This calls the shim generated by our python pipeline (e.g.
  // build/esp32c6_caps.c)
  fz_caps_t caps = chip_get_capabilities();

  // 2. Map capabilities to a safe behavior profile
  fz_profile_t profile = detect_profile(caps);

  // Arm the profile-aware logger policy engine
  fz_logger_init(&profile);

  // 3. Optional: Discover runtime safe-zones (like where our Stack currently
  // resides) discover_safe_zones(&caps);

  // 4. Output the 8-byte Profile Header (Contract with Python Host Scanner)
  fz_log("\n\nBOOT_OK [id:");
  fz_log_hex((uint32_t)profile.id);
  fz_log("] ");
  fz_log(profile.name);
  fz_log("\n");

  fz_log("\n---OSV_ORACLE_READY---\n");

  // Enter Interactive Oracle Mode (Phase 10)
  while (1) {
    uint8_t cmd = 0;
    if (fz_uart_rx_byte(&cmd)) {
      if (cmd == 0xA1) { // 0xA1 = START_SCAN Command
        break;
      }
    }
  }

  // 5. Execute Mathematical Fuzzing
  fuzzer_scan(profile);

  // 6. Output JSON to UART
  fz_log("[CORE] {\"status\": \"complete\"}\n");

  // 7. Safe Halt (Wait for Interrupts)
  while (1) {
    // arch_safe_halt()
  }

  return 0;
}
