/* AUTO-GENERATED BY TOOB MANIFEST COMPILER */
#ifndef GENERATED_BOOT_CONFIG_H
#define GENERATED_BOOT_CONFIG_H

#include <stdint.h>

/* ========================================================================
 * PARTITION MAP (Auto-Generated by Manifest Compiler)
 * ========================================================================
 *   ├──────────────────────────────────────────────────┤ 0x00000000 - 0x00040000
 *   │  [RSVD  ] Hardware Reserved (256 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00040000 - 0x00048000
 *   │  [BOOT  ] Stage 0 (32 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00048000 - 0x00058000
 *   │  [BOOT  ] Stage 1 Bank A (64 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00058000 - 0x00068000
 *   │  [BOOT  ] Stage 1 Bank B (64 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00070000 - 0x000D0000
 *   │  [APP   ] App Slot (384 KB)
 *   ├──────────────────────────────────────────────────┤ 0x000D0000 - 0x00130000
 *   │  [APP   ] Staging Slot (384 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00130000 - 0x00150000
 *   │  [SYSTEM] Recovery OS (128 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00150000 - 0x00160000
 *   │  [APP   ] NetCore Slot (64 KB)
 *   ├──────────────────────────────────────────────────┤ 0x00160000 - 0x001C0000
 *   │  [SYSTEM] Scratch / Delta Safe (384 KB)
 *   ├──────────────────────────────────────────────────┤ 0x001C0000 - 0x001C4000
 *   │  [SYSTEM] WAL Journal (4 sec) (16 KB)
 *   └──────────────────────────────────────────────────┘ 
 *
 * STORAGE SUMMARY:
 *   Physical Flash Size:       4096 KB
 *   Hardware Reserved:          256 KB
 *   Bootloader Core:            160 KB
 *   System & Scratch:           528 KB
 *   Usable App Space:           832 KB
 *   Unallocated / Free:        2288 KB
 * ======================================================================== */

#define CHIP_FLASH_WRITE_ALIGNMENT  4U
#define CHIP_FLASH_BASE_ADDR        0x00000000U

#define CHIP_STAGE1A_ABS_ADDR       0x00048000U
#define CHIP_STAGE1A_SIZE           0x00010000U
#define CHIP_STAGE1B_ABS_ADDR       0x00058000U
#define CHIP_STAGE1B_SIZE           0x00010000U

#define CHIP_APP_SLOT_ABS_ADDR      0x00070000U
#define CHIP_APP_SLOT_SIZE          0x00060000U
#define CHIP_STAGING_SLOT_ABS_ADDR  0x000D0000U
#define CHIP_STAGING_SLOT_SIZE      0x00060000U
#define CHIP_STAGING_SLOT_ID        2U

#define CHIP_RECOVERY_OS_ABS_ADDR   0x00130000U
#define CHIP_RECOVERY_OS_SIZE       0x00020000U
#define CHIP_NETCORE_SLOT_ABS_ADDR  0x00150000U
#define CHIP_NETCORE_SLOT_SIZE      0x00010000U

/* CRITICAL: Must be >= CHIP_APP_SLOT_SIZE for boot_delta_apply output */
#define CHIP_SCRATCH_SLOT_ABS_ADDR  0x00160000U

#define TOOB_WAL_SECTORS            4U

#define TOOB_WAL_SECTOR_ADDRS { \
    0x001C0000U, \
    0x001C1000U, \
    0x001C2000U, \
    0x001C3000U \
}
#define TOOB_WAL_SECTOR_SIZES { \
    4096U, \
    4096U, \
    4096U, \
    4096U \
}

#define BOOT_CRYPTO_ARENA_SIZE      2048U

#define BOOT_WDT_TIMEOUT_MS         4100U

#define CHIP_FLASH_XIP_BASE         0x42000000U

#define CHIP_FLASH_TOTAL_SIZE       0x00400000U
#define CHIP_FLASH_MAX_SECTOR_SIZE  4096U
#define BOOT_CONFIG_MAX_RETRIES     3U
#define BOOT_CONFIG_MAX_RECOVERY_RETRIES 3U
#define BOOT_CONFIG_EDGE_UNATTENDED_MODE 0
#define BOOT_CONFIG_BACKOFF_BASE_S  3600U

#endif /* GENERATED_BOOT_CONFIG_H */
