# ==============================================================================
# Submodule: toob_core (Hardware-Freier Bootloader Kern)
# 
# Relevant Specs: 
# - docs/concept_fusion.md (Schicht 3: Core Engine, Schicht 4b: Diagnostics)
# - docs/structure_plan.md (Verzeichnisbaum `toobloader/core/`)
# - docs/merkle_spec.md (Chunk-based Verification)
# - docs/stage_1_5_spec.md (UART Recovery)
# - docs/wal_internals.md (Write-Ahead Log)
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. Externes Tooling / Vendored Third-Party
# ------------------------------------------------------------------------------
# Wir isolieren Third-Party Code absichtlich in eigene statische Targets.
# Dadurch bewahren wir diese Bibliotheken davor, von unserem knallharten
# `-Werror` & P10-Regelwerk aus `toob_apply_strict_flags` zerrissen zu werden.

# zcbor (Apache-2.0)
add_library(toob_zcbor STATIC 
    common/lib/zcbor/src/zcbor_decode.c
    common/lib/zcbor/src/zcbor_common.c
    common/lib/zcbor/src/zcbor_encode.c
)
target_include_directories(toob_zcbor PUBLIC common/lib/zcbor/include)

# P10 Manifest Malleability Defense (GAP Fix)
# Erzwingt kanonisches CBOR. Verhindert, dass identische Daten
# durch unterschiedliche CBOR-Repräsentationen unterschiedliche Hashes erzeugen.
target_compile_definitions(toob_zcbor PUBLIC ZCBOR_CANONICAL)
set_target_properties(toob_zcbor PROPERTIES C_VISIBILITY_PRESET hidden)
target_compile_options(toob_zcbor PRIVATE -Os -ffunction-sections -fdata-sections)

# heatshrink (ISC License)
add_library(toob_heatshrink STATIC 
    common/lib/heatshrink/heatshrink_decoder.c
)
# WICHTIG (Zero-Allocation Limit): Ohne dieses Define würde heatshrink via malloc
# dynamisch Dictionary-Speicher anfordern, was das P10-Setup hart crashen würde!
target_compile_definitions(toob_heatshrink PUBLIC 
    HEATSHRINK_DYNAMIC_ALLOC=0 
    HEATSHRINK_STATIC_INPUT_BUFFER_SIZE=128 
    HEATSHRINK_STATIC_WINDOW_BITS=8 
    HEATSHRINK_STATIC_LOOKAHEAD_BITS=4
)
target_compile_options(toob_heatshrink PRIVATE -Os -ffunction-sections -fdata-sections)
target_include_directories(toob_heatshrink PUBLIC common/lib/heatshrink)

# ------------------------------------------------------------------------------
# 2. Toob-Boot Kern (Die State-Machine)
# ------------------------------------------------------------------------------

# Die SUIT-Manifest Parser C-File wird via zcbor Compiler-Tool dynamisch
# anhand von device.toml generiert. Daher müssen wir CMake warnen, dass
# die Datei zur Evaluierungszeit evtl. noch gar nicht im Filebaum liegt.
set(GENERATED_TELEMETRY_ENCODE_C "${CMAKE_BINARY_DIR}/generated/toob_telemetry_encode.c")
set(GENERATED_CLOUD_CMD_C "${CMAKE_BINARY_DIR}/generated/boot_cloud_cmd_decode.c")
set_source_files_properties(${GENERATED_TELEMETRY_ENCODE_C} ${GENERATED_CLOUD_CMD_C} PROPERTIES GENERATED TRUE)

# M-BUILD GAP-Fix: Custom Command zum Aufrufen der SUIT & Config Generation
add_custom_command(
    OUTPUT ${CMAKE_BINARY_DIR}/generated/toob_telemetry_decode.c
           ${GENERATED_TELEMETRY_ENCODE_C}
           ${GENERATED_CLOUD_CMD_C}
           ${CMAKE_BINARY_DIR}/generated/generated_boot_config.h
           ${CMAKE_BINARY_DIR}/generated/stage0_layout.ld
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/generated
    
    # -------------------------------------------------------------------------
    # SUIT & Config Mocking / Generation Bridge
    # -------------------------------------------------------------------------
    # Die eigentliche Generierung erfolgt nun nativ durch die Toob CLI in Go,
    # *bevor* CMake aufgerufen wird. Wir markieren die Dateien nur noch als existent.
    # -------------------------------------------------------------------------
    COMMAND ${CMAKE_COMMAND} -E echo "Manifests generated by Toob CLI"
    COMMENT "Verifying SUIT ZCBOR Artifacts..."
)

# Dieses Target wird von toob_chip und toob_stage0 erwartet!
add_custom_target(generate_manifest
    DEPENDS ${CMAKE_BINARY_DIR}/generated/toob_telemetry_decode.c
            ${GENERATED_CLOUD_CMD_C}
            ${CMAKE_BINARY_DIR}/generated/generated_boot_config.h
            ${CMAKE_BINARY_DIR}/generated/stage0_layout.ld
)


# P10 Krypto-Härtung: Optionale echte Double-Execution der Ed25519 Verifikation.
# Detektiert auch algorithmus-interne Faults auf Kosten von ~30-50ms Boot-Zeit.
option(TOOB_DOUBLE_VERIFY "Enable double-execution of Ed25519 for highest fault resistance (~+30ms)" OFF)

# ------------------------------------------------------------------------------
# 2a. Toob-Boot Utilities (Algorithmen & Hilfsmodule)
# ------------------------------------------------------------------------------
# Reine Hilfsmodule ohne Boot-Ablauflogik. Werden vom Core gelinkt, können aber
# auch unabhängig in Recovery/Stage0/Tests eingebunden werden.
#
# Inhalt: CRC32, COBS (Framing), Merkle-Streaming, Delay/WDT-Integration,
#         Diagnostik-Telemetrie, Energiemodell, Identitäts-KDF, Secure Zeroize.

set(TOOB_UTILS_DIR ${TOOB_CORE_DIR}/utils)

add_library(toob_utils STATIC
    ${TOOB_UTILS_DIR}/boot_cobs.c
    ${TOOB_UTILS_DIR}/boot_crc32.c
    ${TOOB_UTILS_DIR}/boot_delay.c
    ${TOOB_UTILS_DIR}/boot_diag.c
    ${TOOB_UTILS_DIR}/boot_energy.c
    ${TOOB_UTILS_DIR}/boot_identity.c
    ${TOOB_UTILS_DIR}/boot_merkle.c
)

# Architektur-bedingter Ausschluss: In der Sandbox (x86 host) können wir 
# keine Bare-Metal (ARM/Xtensa) Assembler-Anweisungen ausführen.
if(NOT TOOB_ARCH STREQUAL "host")
    target_sources(toob_utils PRIVATE ${TOOB_UTILS_DIR}/boot_secure_zeroize.S)
else()
    target_sources(toob_utils PRIVATE ${TOOB_UTILS_DIR}/boot_secure_zeroize_host.c)
endif()

target_include_directories(toob_utils PUBLIC
    ${CMAKE_SOURCE_DIR}/common/include
    ${TOOB_UTILS_DIR}/include
    ${TOOB_CORE_DIR}/include
    ${CMAKE_BINARY_DIR}/generated
    ${TOOB_SDK_DIR}/libtoob/include
)

toob_apply_strict_flags(toob_utils TRUE)

# ------------------------------------------------------------------------------
# 2b. Toob-Boot Kern (Die State-Machine & Boot-Ablauf)
# ------------------------------------------------------------------------------
# Boot-Pipeline, WAL-Journal, Image-Swapping, Delta-Patching, Krypto-Verifikation,
# Rollback-Protection, Cloud-Commands, Provisioning, Panic/Recovery.

add_library(toob_core STATIC
    ${TOOB_CORE_DIR}/boot_main.c
    ${TOOB_CORE_DIR}/boot_state.c
    ${TOOB_CORE_DIR}/boot_mailbox.c
    ${TOOB_CORE_DIR}/boot_tbm1.c
    ${TOOB_CORE_DIR}/boot_effect.c
    ${TOOB_CORE_DIR}/boot_journal.c
    ${TOOB_CORE_DIR}/boot_verify.c
    ${TOOB_CORE_DIR}/boot_swap.c
    ${TOOB_CORE_DIR}/boot_delta.c
    ${TOOB_CORE_DIR}/boot_rollback.c
    ${TOOB_CORE_DIR}/boot_panic.c
    ${TOOB_CORE_DIR}/boot_provisioning.c
    ${TOOB_CORE_DIR}/boot_confirm.c
    ${TOOB_CORE_DIR}/boot_multiimage.c
    ${TOOB_CORE_DIR}/boot_cloud_cmd.c
    ${TOOB_CORE_DIR}/boot_rstore.c
    ${TOOB_CORE_DIR}/boot_transport.c
    ${TOOB_CORE_DIR}/boot_transport_swapscratch.c
    ${TOOB_CORE_DIR}/boot_transport_oneway.c
    ${TOOB_CORE_DIR}/boot_transport_swapmove.c
    ${TOOB_CORE_DIR}/boot_transport_pointer.c
    ${TOOB_CORE_DIR}/boot_platform_bringup.c
    ${GENERATED_CLOUD_CMD_C}
)

# Harte Abhängigkeits-Schranke: Schützt vor Race-Conditions bei parallelen Builds (ninja -j8)!
# toob_core MUSS zwingend warten, bis der CBOR CodeGen alle Header & Mocks abgeworfen hat.
add_dependencies(toob_core generate_manifest)

if(TOOB_ARCH STREQUAL "host")
    target_compile_definitions(toob_core PUBLIC TOOB_MOCK_TEST)
endif()

if(TOOB_DOUBLE_VERIFY)
    target_compile_definitions(toob_core PRIVATE TOOB_DOUBLE_VERIFY=1)
endif()

# ------------------------------------------------------------------------------
# 3. Include-Pfade & Linking & Härtung
# ------------------------------------------------------------------------------

target_include_directories(toob_core PUBLIC 
    ${CMAKE_SOURCE_DIR}/common/include
    ${TOOB_CORE_DIR}/include 
    ${TOOB_UTILS_DIR}/include
    ${CMAKE_BINARY_DIR}/generated
    ${TOOB_SDK_DIR}/libtoob/include
)

# Bindung an Third-Party Libs, Utilities und dynamische Feature-Verwendung
target_link_libraries(toob_core PRIVATE toob_zcbor toob_heatshrink toob_utils)

# P10 Härtung anwenden (TRUE: wir erlauben -fstack-protector-strong für den Core,
# da hier Arrays bearbeitet werden, anders als in der winzigen Stage 0)
toob_apply_strict_flags(toob_core TRUE)
